project:
  type: book


website:
  sidebar:
    style: "docked"
    search: true

number-depth: 3
book:
  title: "Fast analysis of long gravitational wave signals"
  author: 
    - name: Jacopo Tissino
      affiliations:
      - name: Gran Sasso Science Institute 
        address: Viale F. Crispi, 7 67100 L'Aquila
    - name: Jan Harms
      affiliations:
      - name: Gran Sasso Science Institute 
        address: Viale F. Crispi, 7 67100 L'Aquila
  date: "2026-06-15"
  abstract: "Ten years since the first direct detection of gravitational waves, the field is in bloom. Signals are being detected with higher clarity than ever --- the pinnacle of this so far is the coalescence of black holes dubbed GW250114, which enabled stringent tests of fundamental physics. Our theoretical understanding and computational methods are advancing in step, allowing us to efficiently account for more and more effects. The next generation of detectors will allow for extraordinary physical insights, but some aspects of the current data analysis paradigm will need to change. Ground-based detectors will detect so many signals it will be impractical to expend the resources we currently do for each. Deci-Hertz detectors like the Lunar Gravitational Wave Antenna will observe the same stellar-mass binaries for a long time: this makes the choice of reference frame for the analysis non-trivial, while providing significant scientific value by constraining source parameters and providing early warning."
  downloads: "pdf"
  chapters:
    - index.qmd
    - part: "Parameter estimation and model selection"
      chapters:
      - chapters/data-analysis/pe-methods.qmd
      - chapters/data-analysis/likelihood.qmd
    - part: "Anatomy of a gravitational wave signal"
      chapters:
      - chapters/anatomy/gw250114.qmd
      - chapters/anatomy/intrinsic.qmd
      - chapters/anatomy/extrinsic.qmd
    - part: "Future gravitational wave detectors"
      chapters:
      - chapters/multibanding/einstein-telescope.qmd
      - chapters/multibanding/lgwa.qmd
    - chapters/references.qmd
  page-navigation: true
  repo-url: https://github.com/jacopok/thesis
  repo-actions: [edit, source, issue]
  cover-image: logo-gssi.jpg
  cover-image-alt: |
    GSSI logo. 
