
bibliography: rehear.bib

format:
  html:
    theme: 
      light:
        cosmo
      dark:
        [cosmo, theme_dark.css]
    embed-resources: true
    filters: 
      - pdf-to-webp.lua
  pdf:
    documentclass: scrreprt
    colorlinks: true
    linkcolor: blue
    link-citations: true

execute:
  cache: true
  warning: false


