
bibliography: rehear.bib

format:
  html:
    theme: 
      light:
        cosmo
      dark:
        [cosmo, theme_dark.css]
    embed-resources: false
    filters: 
      - pdf-to-webp.lua
    reference-location: margin
    code-fold: true
    code-summary: "Source code"
  titlepage-pdf:
    documentclass: scrreprt
    colorlinks: true
    linkcolor: blue
    cite-method: biblatex
    fig-width: 6
    fig-height: 3
    link-citations: true
    reference-section-title: "References"
    pdf-engine: xelatex
    titlepage: academic
    titlepage-logo: "logo-gssi.jpg"    
    titlepage-footer: "[Gran Sasso Science Institute](https://gssi.it)"
    titlepage-theme:
      affiliation-style: "numbered-list"
      affiliation-sep: "newline"
    echo: false
    include-in-header:
      text: |
        %\usepackage{unicode-math,polyglossia}
        %\usepackage[sups,osf]{fbb}
        \usepackage[scaled=.95]{cabin} 
        \usepackage[varqu,varl]{inconsolata} 
        %\usepackage{mathpazo}


execute:
  cache: true
  warning: false

csl: bibstyle.csl
