[project]
name = "thesis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "astropy>=5.3.2",
    "cartopy>=0.23.0",
    "cmcrameri>=1.9",
    "dynesty<3",
    "getdist>=1.5.4",
    "gw-frequencies>=0.1.1",
    "gwfish",
    "h5py>=3.12.1",
    "hypothesis>=6.128.2",
    "ipyleaflet>=0.19.2",
    "ipython>=8.18.1",
    "jupyter-cache>=1.0.1",
    "jupyter>=1.1.1",
    "lgwa_response",
    "lunarsky>=0.2.1",
    "matplotlib<3.11.0",
    "numba>=0.60.0",
    "numdifftools>=0.9.41",
    "numpy>=1.26.4",
    "pesummary>=1.6.4",
    "plotly>=6.7.0",
    "pyqt6>=6.10.2",
    "pytest>=8.3.5",
    "qnm>=0.4.4",
    "quarto-cli<1.6",
    "scipy>=1.13.1",
    "seaborn>=0.13.2",
    "snakeviz>=2.2.2",
    "thesis-scripts",
    "tqdm>=4.67.1",
]

[tool.uv.workspace]
members = ["thesis_scripts/thesis_scripts"]

[tool.uv.sources]
thesis-scripts = { path = "thesis_scripts", editable = true }
lgwa_response = { path = "../Documents/lgwa-response", editable = true }

