## Fisher matrix

The Fisher matrix is a common tool in gravitational wave data analysis and forecasting. 
It is defined as the noise-averaged Hessian of the log-likelihood:
$$
F_{ij} = \langle \partial_{i} \partial_{j} \log \mathcal{L}(d|\theta) \rangle _\text{noise}\,.
$$

If the likelihood is written in the Whittle form (see @sec-whittle-likelihood), then this is equal to 
$$
F_{ij} = \left( \frac{\partial h}{\partial \theta_{i}} \bigg| \frac{\partial h}{\partial \theta_{j}} \right) \,.
$$

For a derivation, see @finnDetectionMeasurementGravitational1992 or @vallisneriUseAbuseFisher2008.
This matrix can be interpreted in different ways [@vallisneriUseAbuseFisher2008]: _(i)_ in terms of the frequentist Cramér-Rao bound on the error covariance of an unbiased estimator for the true source parameters, _(ii)_ as the error covariance of the frequentist maximum-likelihood estimator, or _(iii)_ as an estimate of the error covariance of the Bayesian posterior distribution under the assumption that the priors are constant over the range of interest; here we shall focus on option _(iii)_ for consistency with the Bayesian approach in the rest of this work. 

We can approximate the likelihood in the linearized signal approximation (LSA), a Taylor series for the signal around the true value of the parameters $\theta_{0}$ in terms of the deviation $\delta\theta = \theta-\theta_{0}$:
$$
h(\theta) = h(\theta_{0}) + \delta\theta_{i} \frac{\partial h}{\partial \theta_{i}} + \mathcal{O}((\delta\theta)^{2})\,.
$$

In the approximation of , the Whittle likelihood is written as 
$$ \log\mathcal{L}(d | \theta) = -\frac{1}{2} (n|n) + \delta\theta_{i} \left( n\bigg|   \frac{\partial h}{\partial \theta_{i}} \right) - \frac{1}{2} \delta \theta^i \delta \theta^j \mathcal{F}_{ij} + \mathcal{O}((\delta\theta)^{3}) \,.
$$
This is the expression of a multivariate normal distribution, with covariance matrix $\mathcal{C}_{ij} = \mathcal{F}_{ij}^{-1}$.

This expression is written as an expansion in orders of the deviation of the parameters, but the actual requirement for the Fisher approximation is a high value of the (optimal) SNR, which we shall define in @sec-snr, $\rho = \sqrt{ (h_{0}|h_{0}) }$.
In this approach, and based on the LSA approximation to the likelihood, we can compute the first and second moment of the posterior distribution $p(\theta|d) \propto \mathcal{L}(d|\theta) \pi(\theta)$ as a series expansion in orders of $1 / \rho$. 
This is only analytically tractable if the prior distribution $\pi(\theta)$ is constant over the range of interest, or Gaussian and centered around the same point as the posterior.

The expectation value of the noise covariance is then 
$$
\langle \delta\theta_{i} \delta\theta_{j} \rangle _{p(\theta|d)} = F_{ij}^{-1} + \mathcal{O}\left(  \frac{1}{\rho^{3}} \right)\,;
$$
with the addition of a Gaussian prior $\pi(\delta\theta) \propto \exp\left( - \frac{1}{2} P_{ij} \delta\theta_{i} \delta\theta_{j} \right)$ it becomes 
$$
\langle \delta\theta_{i} \delta\theta_{j} \rangle _{p(\theta|d)} = \left( F_{ij} + \frac{P_{ij}}{\rho^{2}} \right)^{-1} + \mathcal{O}\left(  \frac{1}{\rho^{3}} \right)\,.
$$

The Fisher matrix can be complemented by the addition of information from a generic prior distribution by performing rejection sampling on samples extracted from the Gaussian distribution it defines [@iacovelliForecastingDetectionCapabilities2022; @dupletsaValidatingPriorinformedFishermatrix2025].

Several studies [@vallisneriUseAbuseFisher2008;@rodriguezInadequaciesFisherInformation2013;@dupletsaValidatingPriorinformedFishermatrix2025;@santoliquidoFastAccurateParameter2025], some of which include prior distributions through rejection sampling, have found that 
the covariance matrix estimated by inverting the Fisher matrix 
does not reliably represent the posterior covariance matrix 
obtained through the sampling techniques described in this chapter.

Nevertheless, the Fisher matrix can be a useful tool, especially in the context of forecasting, due to the relative ease of its computation compared to full parameter estimation.
It provides a metric on the parameter space, which can be useful when generating template banks, see e.g. @phukonGeometricTemplateBank2025.
In some cases it can be computed analytically, which is useful for the theoretical understanding of the behavior of data analysis pipelines, see @sec-analytic-fisher-calculations.

Fisher integrands are also a useful tools for the understanding of parameter constraints: 
a quantity in the form
$$
\frac{4f}{S_{n}(f)} \bigg| \frac{ \partial h }{ \partial \theta_{i} } \bigg|^{2}
$$
can be integrated in $\text{d}\log f$ to yield the $i$-th entry in the diagonal of the Fisher matrix, which contributes to the computation of the variance of the $i$-th parameter.
It is incomplete information, since it does not account for correlations with other parameters; still, it can provide some qualitative understanding and diagnostics.
We used this tool to describe the way information on the sky position of the source accumulates as a function of time with the Lunar Gravitational Wave Antenna [@cozzumboOpportunitiesLimitsLunar2024].

In practice, the computation of Fisher matrices requires differentiation of the projected waveform onto a detector. This can be accomplished numerically, but it is generally convenient to analytically compute all derivatives where it is possible [@dupletsaGwfishSimulationSoftware2023]. 
For example, the derivative with respect to distance is simply
$$
\frac{ \partial h }{ \partial d_{L} } = - \frac{h}{d_{L}}\,,
$$
since $h \propto 1 / d_{L}$.
If the waveforms and projection allow it, even more of the derivatives can be computed analytically, with the help of automatic differentiation such as that enabled by `jax`
[@iacovelliForecastingDetectionCapabilities2022;@iacovelliSupplementForecastingDetection2022].

### Analytic Fisher calculations {#sec-analytic-fisher-calculations}

#### Timing uncertainty

We can obtain a Fisher estimate for the timing uncertainty of a gravitational wave observation by computing the Shur's complement of the Fisher matrix for time and phase [@groverComparisonGravitationalWave2014;@singerRapidBayesianPosition2016].

The result is expressed in terms of the frequency moments of the signal:^[In some references [@fairhurstTriangulationGravitationalWave2009;@essickFrequencydependentResponsesThird2017] this expression is incorrectly reported as $\langle f^{k} \rangle=(f^{k}h|h)$ (or equivalently in each paper's notation). Without the normalization factor $\rho^{2}$, the two terms in the frequency bandwidth expression scale with $\rho^{2}$ and $\rho^{4}$ respectively, meaning that for high enough SNR the variance becomes negative.]
$$
\langle f^{k} \rangle = \frac{1}{\rho^{2}} (f^{k} h|h)\,.
$$
With these, we can define the frequency bandwidth
$$
\sigma_{f}^{2} = \langle f^{2} \rangle -\langle f \rangle ^{2}
$$
and from it the timing uncertainty
$$
\sigma_{t} = \frac{1}{2\pi\rho\sigma_{f}}\,.
$$

#### Angular resolution

Localizing gravitational wave sources is crucial, and it is quite useful to analytically understand which effects drive it in order to inform detector design.
@wenGeometricalExpressionAngular2010 computed a general Fisher expression for the angular area of a source observed by a network of detectors.

This area is a solid angle defined as 
$$
\Delta \Omega_{1\sigma} = 2 \pi \sqrt{ \langle \delta n_{x}^{2} \rangle \langle \delta n_{y} ^{2} \rangle - \langle \delta n_{x} \delta n_{y} \rangle ^{2} } = 2 \pi \sqrt{ \det C_{\text{sky}} } \,,
$$
where $C_\text{sky}$ is the two-dimensional covariance matrix for the two components of the sky position position vector, $n_{X}$ and $n_{Y}$, which are orthogonal to its true value $n_{z}$.
In a spherical coordinate system with right ascension $\alpha$ and declination $\delta$ we need to add a factor $|\cos \delta|$ to get the correct area element [@iacovelliForecastingDetectionCapabilities2022]. 
This area is defined such that the the probability contained within a similarly shaped contour of area $\Delta\Omega$ around the center is $P(\Delta\Omega) = \exp(-\Delta \Omega / \Delta\Omega_{1\sigma})$, therefore the equivalent area at the $X$ credible level is
$$
\Delta\Omega_{X} = \Delta\Omega_{1\sigma} \log(1-X)\,.
$$

The Fisher expression for the $1\sigma$ area reads [@chuScientificBenefitEnlarging2012]:
$$
\Delta \Omega_{1\sigma} = \frac{4 \sqrt{ 2 } \pi c^{2}}{\sqrt{ \sum_{JKLM} \Delta_{JK}\Delta_{LM} |(\mathbf{r}_{KJ} \times \mathbf{r}_{ML}) \cdot \mathbf{n} |^{2} }}\,,
$$
where the indices $JKLM$ span the available detectors, $\Omega$ is the angular frequency,  whereas
$$
\Delta_{IJ} = \langle \Omega d_{I} | \Omega d_{J} \rangle \delta_{IJ} - \langle \Omega d_{I}| \partial_{k} d_{J} \rangle \langle \partial_{l} d_{J} | \Omega d_{J}\rangle  F_{kl}^{-1}
$$
where $F_{kl}$ is the Fisher matrix on all the parameters describing the signal except for they sky position.

The term $|(\mathbf{r}_{KJ} \times \mathbf{r}_{ML}) \cdot \mathbf{n} |$ is twice the area formed
by the projections of the detectors $J$, $K$, $L$, $M$ onto
the plane orthogonal to the wave propagation direction.

This expression is quite unwieldy in the general case; however, it can be simplified significantly for signals whose intrinsic parameters are assumed to be known. 

For a two-detector network observing a monochromatic wave of (known) frequency $f_{0}$, we get
$$
\Delta\Omega_{\text{2 det}} = \frac{1}{\rho_{N}} \frac{c}{\pi f_{0} D_{\perp}} \sqrt{ \frac{\rho_{N}^{4}}{\rho_{1}^{2} \rho_{2}^{2}} }\,,
$$
while for three detectors we get
$$
\Delta\Omega_{\text{3 det}} = \frac{1}{\rho_{N}^{2}} \frac{c^{2}}{4 \pi f_{0}^{2} A_{\perp}} \sqrt{ \frac{\rho_{N}^{6}}{\rho_{1}^{2} \rho_{2}^{2}\rho_{3}^{2}} }\,.
$$

Here, $\rho_{N} = \sqrt{ \sum_{i} \rho_{i}^{2} }$ is the network SNR, the sum in quadrature of the individual SNRs (see @sec-snr); the quantities $D_{\perp}$ and $A_{\perp}$ are respectively the distance between detectors or their area, projected onto a plane orthogonal to the propagation direction $n$.

An expression can also be computed in the case of a long observation by a single detector, since its orbit around the Sun will effectively make it akin to a large network of detectors. 
@wenGeometricalExpressionAngular2010 give this expression only in the limit of a short observation or one that is longer than an year; the expression for an arbitrary-length observation of a monochromatic signal with frequency $f_{0}$ reads @tissinoGeometryLunarGravitational2026
$$
\Delta\Omega = \frac{c^{2}}{2 \pi f_{0}^{2} \rho^{2}A_{\perp}}\,,
$${#eq-wen-chen-area}
where $A_{\perp}$ is the area spanned by the detector's motion within a plane perpendicular to the source direction.

#### Correlation structure

The Fisher matrix can aid in understanding the correlation structure
of the posterior distribution. 

For example, @singerRapidBayesianPosition2016 used it to come to the conclusion that the extrinsic parameters of a gravitational wave source are overall uncorrelated 
from the intrinsic ones (for definitions see @sec-intrinsic and @sec-extrinsic). 
This is qualitatively due to the fact that the extrinsic parameters are generally measured by _inter-detector_ amplitude
and time of arrival _differences_, while intrinsic parameters are generally measured by _averages_ of amplitude
and phase.

We can validate this by computing the Pearson correlation matrix of a full parameter estimation run:
$$ \rho_{ij} = \frac{C_{ij}}{\sigma_i \sigma_j} \,,
$$
where $C_{ij}$ is the empirical covariance matrix computed from the posterior samples, while $\sigma_i = \sqrt{C_{ii}}$ is the standard deviation of parameter $i$.

Each entry $\rho_{ij}$ will lie between -1 and 1, with values near these extremes 
representing near-perfect (anti)correlation, while values near 0 represent uncorrelated
variables.
This only captures _linear_ correlations, so it does not tell the whole story, 
but it is still quite useful.

```{python}
#| label: fig-correlation-matrix
#| fig-cap: "Correlations between some measured parameters for GW170817. $c_{AL1}$ and $c_{\\phi L1}$ are two calibration parameters for the Livingston detector, included for reference, out of the $\\sim$ 12 calibration parameters per detector used in real analyses. Arrival time and overall phase are not included since they were analytically marginalized in this particular analysis."

# we start from the covariance matrix for an analysis of GW170817
# this is included in the auxiliary data for convenience

import numpy as np
from thesis_scripts.correlation_checkerboard import plot_correlations
from thesis_scripts import data_path

symbols = [
    '$\\mathcal{M}$',
    '$q$',
    '$\\chi_1$',
    '$\\chi_2$',
    '$\\Lambda_1$',
    '$\\Lambda_2$',
    '$d_L$',
    '$\\cos \\iota$',
    'ra',
    'dec',
    '$\psi$',
    '$c_{AL1}$',
    '$c_{\phi L1}$',
]
cov = np.loadtxt(data_path / 'covariance_170817.txt')
plot_correlations(cov, symbols)
```

In @fig-correlation-matrix we see the structure of the correlation matrix for an actual analysis of the neutron star binary GW170817
(specifically, the one from @tissinoCombiningEffectiveonebodyAccuracy2023).
