## Nested sampling {#sec-nested-sampling}

Nested sampling, introduced by Skilling in the early 2000s (@skillingNestedSampling2004, @skillingNestedSamplingGeneral2006), is an algorithm designed to compute the _evidence_ $\mathcal{Z}$ as well as the posterior distribution on the parameters. 

The evidence is computed through the integral

$$ \mathcal{Z}(d|M) = \int \mathcal{L}(d | \theta, M) \pi (\theta | M) \text{d}^n\theta \,.
$$

This integral is in $n$ dimensions (where $n$ is the dimensionality of the parameter space) and therefore difficult to work with. The idea in nested sampling is to rewrite it in terms of the auxiliary variable $X$, defined as the prior volume contained within a likelihood constraint $\mathcal{L} \geq L$:

$$ X (L) = \int_{\mathcal{L}(d | \theta, M) \geq L} \pi (\theta | M) \text{d}^n\theta\,.
$$

Since the prior is a normalized probability distribution and the likelihood ranges from 0 to $L _{\text{max}}$, this variable will range from $X(0) = 1$ to $X(L _{\text{max}}) = 0$, and it will always be decreasing.^[It will not necessarily be _strictly_ decreasing, but that is not a conceptual issue. One can introduce jitter in the likelihood, varying it at each point by an inconsequential amount, in order to ensure that the decreasing condition is verified precisely.]
We can define its inverse, $L(X)$, 
and rewrite the likelihood integral through integration by parts: the evidence is the expectation value of the likelihood, therefore, starting from the definition of a Lebesgue integral:
$$
\mathcal{Z}(d|M) = \int_{0}^{L_\text{max}} X(L) \text{d}L 
= X L |_{L=0}^{L=L_\text{max}} - \int_{X(L=0)}^{X(L=L_\text{max})} L(X)\text{d}X = \int_{0}^{1}L(X)\text{d}X\,.
$$ {#eq-evidence-integral}

For a detailed discussion of the mathematical details, also see @ashtonNestedSamplingPhysical2022, @siviaDataAnalysisBayesian2006.

### Prior compression {#sec-prior-compression}

Note that, by definition, $X$ is directly related to probability mass: the prior probability of an interval $[X_{0}, X_{1}]$, i.e. the prior mass which has likelihood values $L(X_{1}) < \mathcal{L} < L(X_{0})$, is 

$$
p([X_{0}, X_{1}]) = \int _{L(X_{0}) < \mathcal{L}(d|\theta, M) < L(X_{1})} \pi (\theta | M) \text{d}^{n} \theta = X_{1} - X_{0}\,,
$$

where we computed the integral on a likelihood "ring" by subtracting the inside volume from the outside one.
This is useful to us, since it means that if we distribute points according to the prior their $X$ values will also be uniformly distributed in $[0, 1]$. 
More formally, the probability we are assigning to $X$ is the _push-forward_ probability measure associated to the mapping from $\theta$ to $X$ defined by $X(\theta) = X(L(\theta))$.
For a discussion on this, see [@ashtonNestedSamplingPhysical2022, box 2].

If $k$ points are uniformly distributed in an interval $[0, X^*]$, then the largest of them will have a $X$ coordinate distributed as $X _\text{max} / X^* \equiv t \sim \text{beta}(k, 1) = k t^{k-1}$, where we defined the _compression ratio_ $t$: when we discard the lowest-likelihood point with $X _\text{max}$, we will have contracted the prior volume by a factor $t$. 

::: {#nte-beta-distribution .callout-note collapse="true"}
##### On the beta distribution

Here is a simple argument for why $t$, the largest out of $k$ uniform random variates in $[0, 1]$, is distributed according to $t \sim k t^{k-1}$. 
The statement can equivalently be framed in terms of the cumulative distribution: $p(t \leq T) = T^{k}$.

We can think of our $k$ random variates as a point in the $k$-dimensional unit box $[0, 1]^{k}$, and since they are uniformly distributed there will be a one-to-one correspondence between volume within the box and probability mass.
Then, the geometric meaning of the cumulative distribution is: what is the volume of the region corresponding to the event $t \leq T$, i.e. such that the maximum of the coordinates of our point is $T$?
The answer is the box $[0, T]^{k}$, whose volume is $T^{k}$, thus proving our claim.

In general, the $n$-th smallest out of $k$ uniform random variates in $[0, 1]$ is distributed according to a beta distribution, specifically $\text{beta}(k, n-k+1) \propto x^{n-1}(1-x)^{k-n}$; here we are looking at the $k$-th smallest (i.e. the largest).
:::

In terms of $\log t$, the distribution reads 
$$
\frac{\text{d}p}{\text{d}\log t} = t\frac{\text{d}p}{\text{d}t} = k t^{k} = k e^{k \log t}
$$

This distribution is shown in @fig-nested-sampling-volume-compression-distribution.

```{python}
#| label: fig-nested-sampling-volume-compression-distribution
#| fig-cap: "Volume compression"

from matplotlib.ticker import FixedLocator, FixedFormatter
import numpy as np
import matplotlib.pyplot as plt

plt.figure(figsize=(6, 2.5))

n = 1
log_t = np.linspace(-3/n, 0)
p_of_log_t = n * np.exp( n * log_t)

plt.plot(log_t, p_of_log_t / n)
_ = plt.xlabel('$\log t$')
_ = plt.ylabel(r'$\mathrm{d}p / \mathrm{d} \log t$')

plt.xlim(-3/n, 0)
plt.ylim(0, n)

plt.gca().xaxis.set_major_locator(FixedLocator([-3/n, -2/n, -1/n, 0]))
plt.gca().xaxis.set_major_formatter(FixedFormatter([
	'$-3/n$', 
	'$-2/n$', 
	'$-1/n$', 
	'$0$'
]))

plt.gca().yaxis.set_major_locator(FixedLocator([0, n/4, n/2, 3*n/4, n]))
plt.gca().yaxis.set_major_formatter(FixedFormatter([
	'$0$', 
	'$n/4$', 
	'$n/2$', 
	'$3n/4$', 
	'$n$'
]))
```

Its mean and standard deviation are: 
$$
\begin{aligned}
\langle \log t \rangle &= \int_{-\infty}^{0} \log t \frac{\text{d}p}{\text{d}\log t} \text{d}\log t  \\
&= \int_{-\infty}^{0} \frac{x}{k} k e^{x} \frac{ \text{d}x}{k}  \\ 
&= \frac{1}{k} \int_{-\infty}^{0} x e^{x} \text{d}x \\
&= - \frac{1}{k}
\end{aligned}
$$

where $x = k \log t$, and
$$
\begin{aligned}
\left\langle  (\log t)^{2}  \right\rangle - \frac{1}{k^{2}}
&= \int_{-\infty}^{0} (\log t)^{2} \frac{\text{d}p}{\text{d}\log t} \text{d} \log t - \frac{1}{k^{2}} \\
&= \int_{-\infty}^{0} \frac{x^{2}}{k^{2}} k e^{x} \frac{\text{d}x}{k} - \frac{1}{k^{2}}  \\
&= \frac{1}{k^{2}} \int_{-\infty}^{0} x^{2} e^{x} \text{d}x - \frac{1}{k^{2}}  \\
&= \frac{2-1}{k^{2}} = \frac{1}{k^{2}}\,.
\end{aligned}
$$

Compactly, we can then write $\log t = (-1 \pm 1) / k$. 

### Computing evidence and posterior

If we sample $k$ points from the prior (with total volume $X_{0}$) and remove the one with the worst likelihood, the remaining prior volume will be $X_{1} = t_{1}X_{0}$, where $\log t_{1}$ has an expectation value of $-1 /k$. This will be true at every iteration, so [@skillingNestedSamplingGeneral2006, section 5]
$$
\log X_{i} = \sum_{j\leq i} \log t_{j} \approx -\frac{i}{k} \pm \frac{\sqrt{ i }}{k}\,.
$$

The prior is compressed exponentially, which is desirable since the typical set for the posterior is often several orders of magnitude smaller than the prior.

```{python}
#| label: fig-nested-sampling-volume-compression-iteration
#| fig-cap: "Volume compression by iteration. The number of live points is denoted here as $n_{\\mathrm{live}} = k$. Note how the horizontal slices are thinner when we have more live points: increasing them will decrease the uncertainty on the prior compression obtained at a fixed iteration number. After reaching a logarithmic volume compression of $- \\log X = 4$ the runs are truncated, and the remaining points are shown: these are distributed uniformly and not geometrically in $X$, therefore they taper off in this logarithmic plot."

import numpy as np
import matplotlib.pyplot as plt

rng = np.random.default_rng(seed=1)

n_iterations = 80
logX_min = -4

n_live_numbers = [100, 50]
colors = ['grey', 'black']

plt.figure(figsize=(6, 3.))

for n_live, color in zip(n_live_numbers, colors):

	results = [[] for _ in range(n_iterations)]

	for i in range(n_iterations):
		points = rng.uniform(size=n_live)
		points = np.sort(points)
		logX = 0
		while logX > logX_min:
			results[i].append(logX)
			logX = np.log(points[-1])
			points[-1] = rng.uniform(0, np.exp(logX))
			points = np.sort(points)
		results[i].extend(np.log(points[::-1]))

	min_i = min(len(arr) for arr in results)

	for i in range(n_iterations):
		if i == 0:
			label = '$n_{\mathrm{live}} =$' + f' {n_live}'
		else:
			label = None
		plt.plot(
			results[i], 
			np.arange(len(results[i])), 
			c=color, 
			alpha=.2, 
			label=label)

plt.legend()
plt.axvline(logX_min, ls='--', c='black', lw=1)
plt.xlim(0, logX_min-6)
plt.xlabel(r'$\log X$: prior compression')
plt.ylabel('Iteration number')
plt.show()
```

This allows us to construct a procedure to evaluate the integral in @eq-evidence-integral, as long as we are able to do the following:

1. sample $k$ points from the prior;
2. find the lowest-likelihood point $\theta_{1}$ and discard it: now the prior volume is approximately $X_{1} = e^{-1/k}$, let us denote its likelihood as $L_{1}$;
3. sample a new point $\theta_{2}$ from the prior, constrained to $L_{2} = L(\theta_{2}) > L_{1}$;
4. repeat from point 2.

We are constructing a sequence of discarded ("dead") points $\theta_{i}$ with corresponding likelihoods $L_{i}$ and approximate associated interior prior volumes $X_{i} \approx e^{-i/k}$. 
At this stage, we still need to discuss how step 3 is performed, as well as when the iteration should stop --- for now, suppose that happens at some stage $n_\text{iter}$.

For the evidence, we can simply use a trapezoidal integration rule: 
$$
\mathcal{Z}(d|M) \approx  \sum_{i=1}^{n_\text{iter}} w_{i} L_{i} = \sum_{i=1}^{n_\text{iter}} \frac{X_{i+1} - X_{i-1}}{2} L_{i} 
$$

It can be shown that this sum converges to the correct value in the $n_\text{iter} \to \infty$ and $n _\text{live} \to \infty$ limit.

These weights can also be used to estimate the posterior as follows: take the points $\theta_{i}$ and assign to each of them a weight 
$$
p_{i} = \frac{w_{i} L_{i}}{Z}\,.
$$

These weighted samples (see @sec-weighted-samples) represent the posterior.
It is readily seen that these weights add to 1, and heuristically they are computed as one might expect, by multiplying the prior mass and likelihood value for each of the regions we have subdivided the prior volume into.

### Sampling options {#sec-ns-sampling-options}

Nested sampling is, in a way, a meta-algorithm: the sub-algorithm used to sample a new point from the prior subject to the constraint that its likelihood be higher than the last rejected point is a crucial determinant of the computational complexity and behavior of the implementation.
This problem is called Likelihood-Restricted Prior Sampling.

A review of several possible options can be found in [@buchnerNestedSamplingMethods2021, section 5] or [@ashtonNestedSamplingPhysical2022, table 2]. Roughly speaking, they can be classified into:

- MCMC-based methods;
- region-based methods;
- machine learning-based methods.
- hybrid methods;

While the current set of live points is often used as a guide, the statistical properties of nested sampling hold as long as the new point is uncorrelated from the previous ones.

#### The prior transform

The way most nested sampling software implements likelihood-restricted prior sampling starts from the assumption that the prior is uniform in the box $[0, 1]^{d}$.

This seems restrictive at first glance, but does not actually constrain the class of models we can consider.
For any given prior $\pi(\theta)$ we want to use, it means that we need to find a mapping $g\colon [0, 1]^{d} \to \mathbb{R}^{d}$  between the unit $d$-dimensional box and our physical prior space, such that if $u \sim \mathcal{U}([0, 1]^{d})$, then $g(u) \sim \pi$, i.e. mapping uniformly-distributed random numbers onto values distributed according to our prior.

If our prior is _separable_, i.e. $\pi (\theta) = \prod_{i=1}^{d} \pi_{i}(\theta_{i})$, then the problem is solvable analytically: the prior transform map will be  such that
$$
g(u) = [\text{CDF}^{-1}_{\pi_{i}}(u_{i})]_{i}
$$
where "CDF" denotes the cumulative distribution of $\pi_{i}$:
$$
\text{CDF}_{\pi_{i}} (\theta_{i}) = \int_{-\infty}^{\theta_{i}} \pi_{i}(y) \text{d}y \in [0,1]
$$
and $\text{CDF}^{-1}$ is its inverse. 
The cumulative distribution can also be computed from samples, so in the case of separate priors we need not have an analytical expression for them.

In the non-separable case there is no general procedure to accomplish this, which is equivalent to stating that there is no algorithm to "analytically" sample from an arbitrary distribution.
This restricts the space of usable priors, since we need to be able to sample from them. 
Typically, we use priors with known analytical expressions.

### Model comparison with nested sampling

In order to illustrate the process of model comparison, let us define a simple problem: 
suppose we have a set of data points $(x_{i}, y_{i})$ with constant, known and Gaussian uncertainties $\sigma_{y}$ on the $y$ values.

We will compare two simple _nested_ models, namely a parabolic one with $y = f(x; a, b, c) = a x^{2}+bx+c$ and a linear one with $y = f(x; b, c) = bx+c$. 
Model comparison can also be performed for non-nested models, but the nested case has some nice properties we will showcase later.

Let us generate the data and plot it: it will come from the parabolic model.

```{python}
#| label: fig-parameter-estimation-parabolic-data
#| fig-cap: Toy model, with data coming from a parabolic function and Gaussian errors.

import numpy as np
import matplotlib.pyplot as plt
from thesis_scripts import data_path

kwargs = {
	'fmt': 'o',
	'capsize': 5,
	'alpha': .8,
}

rng = np.random.default_rng(seed=1)

n_points = 20

x_i = np.linspace(-5, 5, num=n_points)
sigma_y = 1
true_a = -0.1
true_b = 0.5
true_c = 3

def model(x, a, b, c):
	return a*x**2 + b*x + c

y_i = model(x_i, true_a, true_b, true_c) + rng.normal(scale=sigma_y, size=n_points)

_ = plt.errorbar(x_i, y_i, sigma_y, **kwargs)
_ = plt.xlabel('$x$')
_ = plt.ylabel('$y$')

np.save(data_path / 'cache' / 'parabolic_data_x.npy', x_i)
np.save(data_path / 'cache' / 'parabolic_data_y.npy', y_i)
```

We can then analyze this data, using a Gaussian likelihood and setting (somewhat arbitrarily) uniform priors for the parameters $a$, $b$ and $c$ in the range $[-10, 10]$: 

- $\pi(a, b, c) = 1 / 20^{3}$ in that range and 0 otherwise for the parabola;
- $\pi(b, c) = 1 / 20^{2}$ in that range and 0 otherwise for the parabola;

The log-likelihood will be 
$$
\log \mathcal{L}(\text{data} | \theta, \text{model}) = - \frac{1}{2}  \sum_{i=1}^{n} \frac{(y_{i} - f(x_{i}; \theta))^{2}}{\sigma_{y}^{2}} - \frac{n}{2} \log (2 \pi \sigma_{y}^{2}).
$$


```{python}
from dynesty import DynamicNestedSampler

lnorm = -0.5 * (
	np.log(2 * np.pi) * n_points +
    np.log(sigma_y**2 * n_points))

def loglike(theta):
	y = model(x_i, *theta)
	return - 0.5 * ((y-y_i)**2).sum() / sigma_y**2 + lnorm

def loglike_linear(theta):
	y = model(x_i, 0, *theta)
	return - 0.5 * ((y-y_i)**2).sum() / sigma_y**2 + lnorm

def prior_transform(u):
	# flat prior in [-10, 10] for all parameters
	return u*20. - 10.

fname = data_path / 'cache' / 'parabolic_model.pkl'

if fname.exists():
	sampler_parabola = DynamicNestedSampler.restore(str(fname))
else:
	sampler_parabola = DynamicNestedSampler(loglike, prior_transform, 3, nlive=500)
	sampler_parabola.run_nested(dlogz_init=0.01)
	sampler_parabola.save(str(fname))
```

```{python}
fname = data_path / 'cache' / 'linear_model.pkl'

if fname.exists():
	sampler_linear = DynamicNestedSampler.restore(str(fname))
else:
	sampler_linear = DynamicNestedSampler(loglike_linear, prior_transform, 2, nlive=500)
	sampler_linear.run_nested(dlogz_init=0.01)
	sampler_linear.save(str(fname))
```

We perform Bayesian inference for the two models with Nested Sampling (@sec-nested-sampling). It gives us estimates for the posterior distributions of the parameters as well as the evidences.
This allows us to compute a Bayes Factor:
$$
\log \text{BF}^{\text{parabola}}_\text{line} = \log Z_\text{parabola} - \log Z_\text{line}\,,
$$

which appears in the equation for the posterior odds for one model against the other:
$$
\underbrace{ \frac{p(M_\text{parabola} | d)}{P(M_\text{line}| d)} }_{ \text{posterior odds} } 
= \text{BF}^{\text{parabola}}_{\text{line}} \underbrace{ \frac{p(M_{\text{parabola}})}{p(M_{\text{line}})} }_{ \text{prior odds} }\,.
$$


```{python}
from IPython.display import Markdown
bayes_factor = sampler_parabola.results.logz[-1] - sampler_linear.results.logz[-1]
bf_error = np.sqrt(
	sampler_parabola.results.logzerr[-1]**2 + 
	sampler_linear.results.logzerr[-1]**2
)

Markdown(
	'In this case, the curvature of the data is strong enough for the Bayes Factor to favor the parabolic model (although not by much): '
	f'the log Bayes factor is ${bayes_factor:.2f}\pm$ {bf_error:.2f} nats in favor of the parabolic model.')
```

Since the models we are considering were nested, we have a comparison point for our Bayes Factor: the Savage-Dickey density ratio; see @eq-savage-dickey-density-ratio.

The linear model is indeed a special case of the parabolic one (with $a=0$); the priors for the other parameters are exactly the same in both cases. Then:
$$
\text{BF}^{\text{parabola}}_\text{line} = \frac{p(a=0 | d, M_\text{parabola})}{\pi(a=0|M_\text{parabola})}\,.
$$

One might then think that, at least in this type of scenario, going through the evidence computation with a powerful tool such as Nested Sampling was unnecessary: the posterior distribution can be computed for cheaper, after all.
However, as we show in @fig-savage-dickey, computing the value for the posterior density distribution at the point $a=0$ is not easy. 

We can approximate the posterior density based on the samples with tools like a histogram or a kernel density estimate, but any such method will suffer from low statistics if we need to explore the edges of the distribution, as we see here: we would need an enormous amount of posterior samples to reach the same accuracy on the ratio of the distributions we get with Nested Sampling.

```{python}
#| label: fig-savage-dickey
#| fig-cap: "Consistency of the Savage-Dickey density ratio and Nested Sampling estimates for the Bayes Factor. The blue curve is the prior on _a_ under the parabolic model, the dark and light red curves are respectively a KDE reconstruction and histogram of the posterior distribution on _a_ under the parabolic model. The dashed vertical line is the true value of _a_. Finally, the black dot represents the equivalent posterior-to-prior ratio to the Bayes Factor obtained through nested sampling. The value is broadly consistent with what one can obtain by approximating the posterior, but it is much more precise and its error is better quantified."

from scipy.stats import gaussian_kde
a_samples = sampler_parabola.results.samples[:, 0]
a_weights = sampler_parabola.results.importance_weights()

a_range = [-0.25, 0.05]
cmap = plt.get_cmap('coolwarm')

a_values = np.linspace(*a_range, num=50)

values, edges = np.histogram(a_samples, bins=a_values, density=True, weights=a_weights)
kde = gaussian_kde(a_samples, weights=a_weights)

plt.stairs(values, edges, alpha=.5, color=cmap(1.))
plt.plot(a_values, kde(a_values), alpha=.9, color=cmap(1.))

_ = plt.axhline(1/20, alpha=.9, color=cmap(0.))
_ = plt.axvline(true_a, ls='--', lw=1, c='black')
_ = plt.yscale('log')
_ = plt.xlim(*a_range)
_ = plt.ylim(1e-3, 5e1)
posterior_at_0 = 1/20 * np.exp(-bayes_factor)
_ = plt.errorbar(0, posterior_at_0, posterior_at_0* bf_error, **kwargs, color='black')


_ = plt.arrow(0, 1/20, 0, 1/20*(np.exp(-bayes_factor)-1), length_includes_head=True, color=cmap(0.), alpha=.5, width=0.003)

_ = plt.xlabel('$a$')
_ = plt.ylabel('Marginal posterior and prior densities $[\mathrm{d}p / \mathrm{d} a]$')

ax = plt.gca()

x1, x2, y1, y2 = -0.01, 0.01, posterior_at_0*0.7, posterior_at_0*1.3  # subregion of the original image
axins = ax.inset_axes(
    [0.6, 0.6, 0.37, 0.37],
    xlim=(x1, x2), ylim=(y1, y2), xticklabels=[], yticklabels=[])
axins.arrow(0, 1/20, 0, 1/20*(np.exp(-bayes_factor)-1), length_includes_head=True, color=cmap(0.), alpha=.5, width=0.03)
axins.errorbar(0, posterior_at_0, posterior_at_0* bf_error, **kwargs, color='black')
axins.stairs(values, edges, alpha=.5, color=cmap(1.))
ax.indicate_inset_zoom(axins, edgecolor="black")
_ = axins.plot(a_values, kde(a_values), alpha=.5, color=cmap(1.))

```


### Commonly used plots

The quantities we discussed can be tracked through a Nested Sampling run as a useful diagnostic. 
Here we show some commonly used plots, based on a two-dimensional example where the likelihood is Gaussian in the parameters.
The assumptions are as follows: 

- our prior is a $2$-dimensional uniform distribution $\pi \sim \mathcal{U}([0,1]^2)$;
- our likelihood is a $2$-dimensional normal distribution, with mean $\mu = [0.5, 0.5]$ and correlated covariance matrix 
$$
C = 3 \times 10^{-2} \begin{pmatrix}
1 & 0.95 \\
0.95 & 1
\end{pmatrix}
$$

We use 400 live points, and stop iterating when the contribution to the integral from a single iteration reaches $\Delta \log Z_{i} < 0.01$.
We use the `dynesty` sampler [@speagleDYNESTYDynamicNested2020].

```{python}
import numpy as np
from dynesty import NestedSampler
from thesis_scripts import data_path

# from the Dynesty quickstart: 
# https://dynesty.readthedocs.io/en/latest/quickstart.html
ndim = 2

# Define our 3-D correlated multivariate normal log-likelihood.
std = 3e-2
mu = 0.5 * np.ones(ndim)
C = np.identity(ndim) * std**2
C[C==0] = 0.95 * std**2
Cinv = np.linalg.inv(C)
lnorm = -0.5 * (np.log(2 * np.pi) * ndim +
                np.log(np.linalg.det(C)))

def loglike(x):
    return -0.5 * np.dot(x-mu, np.dot(Cinv, x-mu)) + lnorm

def ptform(u):
    return u

fname = data_path / 'cache' / 'plotting_example_sampler.pkl'

if fname.exists():
	sampler = NestedSampler.restore(str(fname))
else:
	sampler = NestedSampler(loglike, ptform, ndim, nlive=400)
	sampler.run_nested(dlogz=0.01)
	sampler.save(str(fname))

```

#### Run plot

The first diagnostic tool is the _run plot_, where we see the accumulation of the evidence integral as a function of the prior compression $\log X$

- the number of live points, which is constant up to the point where the nested sampling run is stopped: then, the remaining points are reused;
- the likelihood $L_i$, which is strictly increasing as expected;
- the posterior mass $w_i L_i / Z$, which increases and then decreases: first, the likelihood's increase dominates, but at some point its values start tapering, and the decrease in prior volume $w_i$ dominates;
- the accumulation of evidence, with a corresponding error estimated as discussed in @sec-information-gain.

```{python}
#| label: fig-nested-sampling-runplot
#| fig-cap: A run plot, illustrating the progress of a nested sampling run.

from dynesty import plotting as dyplot
lnz_truth = 0
fig, axes = dyplot.runplot(sampler.results, lnz_truth=lnz_truth)
fig.set_size_inches(8, 8)
```


#### Trace plot

The following plot is called a _trace plot_, which relates the evolution in prior compression to the actual values of the parameters.
For each parameter, we get a scatter plot of its value as a function of the prior compression, and we can see its range shrink as we reach higher and higher values of the likelihood.

More specifically, this plot is showing the locations of the _dead points_, i.e. the lowest-likelihood points that get discarded at each iteration.
When one of them gets replaced, it will be assigned a new likelihood in the range $[L_{i}, L_\text{max}]$, and after a certain number of iterations it will be replaced again. This is what the red lines are showing; they should be moving "randomly" across the parameter space, if we were to see them remain in a given region in the parameter space we would have an indication that our replacement algorithm is not performing properly.

The points are colored by their importance weights, $w_{i}L_{i} / Z$, and to the right we see a density estimate plot for the posterior distribution of each parameter together with a 95% confidence interval.

```{python}
#| label: fig-nested-sampling-traceplot
#| fig-cap: A trace plot, illustrating the parameter constraints for a nested sampling run.

fig, axes = dyplot.traceplot(
	sampler.results, 
	truths=np.zeros(ndim),
	truth_color='black', 
	show_titles=False,
	trace_cmap='inferno', 
	connect=True,
	connect_highlight=range(2)
)
fig.set_size_inches(6, 3.5)

```

#### Corner plot

The _corner plot_ is a great tool to extract physical understanding about our model. 
It shows the marginal density plot for all our parameters, as well as for each pair of parameters.

```{python}
#| label: fig-nested-sampling-cornerplot
#| fig-cap: A corner plot, showing correlations in the posterior distribution.

fig, axs = dyplot.cornerplot(
	sampler.results, 
	color='blue', 
	truths=np.zeros(ndim),
	truth_color='black', 
	show_titles=True,
	max_n_ticks=3, 
	quantiles=None,
)
fig.set_size_inches(5, 3)
```

#### Posterior predictive density plot

For this example the previous example is not adequate, so we will use the problem from @sec-model-comparison.

Is our model able to reproduce the data? 
A convenient visualization to gain insight into this question is the _posterior predictive distribution_: the distribution expected of new data, conditional on our model and the data we observed.

$$
\begin{aligned}
p(y_\text{pred} | y _\text{obs}, M) &= \int p(y_\text{pred}, \theta|y_\text{obs}, M)\text{d}\theta \\
&= \int p(y_\text{pred}|\theta, y_\text{obs}, M) p(\theta | y_\text{obs}, M)\text{d}\theta  \\
&= \int \underbrace{p(y_\text{pred}|\theta, M)}_{\text{model}} \underbrace{ p(\theta | y_\text{obs}, M) }_{ \text{posterior} }\text{d}\theta
\end{aligned}
$$

We can show this in different ways; an easy one to implement is by drawing samples from the posterior and plotting the model realization corresponding to each of them. The ensemble of curves will follow the posterior predictive distribution. 

```{python}
#| label: fig-nested-sampling-ppd
#| fig-cap: A posterior predictive density plot, sketching the posterior densities by plotting 100 curves sampled from the posterior.

from dynesty import DynamicNestedSampler

x_i = np.load(data_path / 'cache' / 'parabolic_data_x.npy')
y_i = np.load(data_path / 'cache' / 'parabolic_data_y.npy')

kwargs = {
	'fmt': 'o',
	'capsize': 5,
	'alpha': .8,
}


sigma_y = 1
true_a = -0.1
true_b = 0.5
true_c = 3
n_points = len(x_i)

lnorm = -0.5 * (
	np.log(2 * np.pi) * n_points +
    np.log(sigma_y**2 * n_points))

def loglike(theta):
	y = model(x_i, *theta)
	return - 0.5 * ((y-y_i)**2).sum() / sigma_y**2 + lnorm

def loglike_linear(theta):
	y = model(x_i, 0, *theta)
	return - 0.5 * ((y-y_i)**2).sum() / sigma_y**2 + lnorm

def prior_transform(u):
	# flat prior in [-10, 10] for all parameters
	return u*20. - 10.

fname_parabola = data_path / 'cache' / 'parabolic_model.pkl'

if fname_parabola.exists():
	sampler_parabola = DynamicNestedSampler.restore(str(fname_parabola))
else:
	sampler_parabola = DynamicNestedSampler(loglike, prior_transform, 3, nlive=500)
	sampler_parabola.run_nested(dlogz_init=0.01)
	sampler_parabola.save(str(fname_parabola))

fname_linear = data_path / 'cache' / 'linear_model.pkl'

if fname_linear.exists():
	sampler_linear = DynamicNestedSampler.restore(str(fname_linear))
else:
	sampler_linear = DynamicNestedSampler(loglike_linear, prior_transform, 2, nlive=500)
	sampler_linear.run_nested(dlogz_init=0.01)
	sampler_linear.save(str(fname_linear))


def model(x, a, b, c):
	return a*x**2 + b*x + c


plt.errorbar(x_i, y_i, 1, **kwargs, c='black')
plt.xlabel('$x$')
plt.ylabel('$y$')

cmap = plt.get_cmap('coolwarm')

for posterior_sample in sampler_parabola.results.samples_equal()[:100]:
	plt.plot(x_i, model(x_i, *posterior_sample), c=cmap(0.), alpha=.1)

for posterior_sample in sampler_linear.results.samples_equal()[:100]:
	plt.plot(x_i, model(x_i, 0, *posterior_sample), c=cmap(1.), alpha=.1)

```

For an in-depth discussion of posterior predictive checks in the context of gravitational wave data analysis, see [@romero-shawWhenModelsFail2022].

### Information gain {#sec-information-gain}

The typical set of the posterior is often "much smaller" than the prior: how can this be quantified?
A useful way to do so is the relative entropy, or Kullback-Leibler divergence between posterior and prior, often also called  _information gain_ or $H$:

$$ H = \text{KL}(p \parallel \pi) = \int p(\theta ) \log \left( \frac{ p( \theta )}{\pi (\theta )}\right) \text{d}\theta = \int p(X) \log p(X) \text{d}X\,.
$$

The base of the logarithms defines the unit used for the information gain:

- if they are natural logarithms (base $e$) the values are in _nats_;
- if they are base 2 logarithms, the values are in _Shannons_ or _bits_;
- if they are base 10 logarithms, the values are in _Hartleys_ or _dex_.

One way to interpret this is related to the signal-to-noise ratio [@siviaDataAnalysisBayesian2006, eq. 9.15]:
$$
H \sim \text{\# active components in the data} \times \log\text{(signal-to-noise ratio)}
$$

It can also be seen as a "volumetric compression" from the prior to the posterior.
If the distributions are uniform, this intuition is exact [@petrosyanSuperNestAcceleratedNested2022]: suppose we have $\pi (\theta) \equiv [\theta \in V_{\pi}] / V_{\pi}$ and $p(\theta) \equiv [\theta \in V_{p}] / V_{p}$, where the two volumes are such that $V_{p} \subset V_{\pi}$.^[The square brackets are the Iverson bracket, as defined by @knuthTwoNotesNotation1992.] Then,  
$$
\text{KL} (p \parallel \pi) = \int_{V_{\pi}} \frac{[\theta \in V_{p}]}{V_{p}} \log \frac{V_{\pi}}{V_{p}} \text{d}\theta = \log \frac{V_{\pi}}{V_{p}},
$$

The integral can be restricted to the $V_{p}$ volume, since the integrand is zero outside it.
Another useful special case to develop an intuition is the one in which our prior is a Gaussian distribution with standard deviation $\sigma$, and our posterior is centered on the same value but its standard deviation is $\sigma' = \sigma / k$.
Then, the information gain is [@buchnerIntuitionPhysicistsInformation2022]:
$$
\text{KL}(\mathcal{N}(\mu, \sigma') \parallel \mathcal{N}(\mu, \sigma)) = \log k + \frac{1}{2} \left(  \frac{1}{k^{2}} - 1 \right)\,.
$$

We can compute the theoretical value for the entropy in the example above, since the computation is analytic in the Gaussian case: it is known that the differential entropy of a $d$-dimensional multivariate Gaussian random variable $f \sim \mathcal{N}(\mu, C)$ is [@coverElementsInformationTheory2006, theorem 8.4.1]:
$$
- \int_{\mathbb{R}^{d}} f(\theta) \log f(\theta) \ \text{d}^{d}\theta = \frac{d}{2}\log(2 \pi e) + \log \det C \,.
$$

The integral we need to compute $H$ is very similar. The sign is opposite, and instead of being over $\mathbb{R}^{2}$ it is only over $[0, 1]^{2}$. The region outside of this box is, however, more than $10\sigma$ from the mean, therefore its contribution is negligible.

```{python}
from IPython.display import Markdown

Markdown(
	'Comparing the analytical result with an estimate computed during the run by the sampler, we see that '
	f'they are quite similar: the value of $H$ obtained during sampling is {sampler.results.information[-1]:.2f}, while the '
	f'analytical estimate is {-ndim/2 * (1+np.log(2 * np.pi)) - .5 * np.log(np.linalg.det(C)):.2f}.')
```

#### Algorithm termination

The nested sampling algorithm we described above could continue forever, with ever-smaller compression $\log X$. However, if the likelihood function is bounded, after a certain number of iterations the prior volume will be concentrated around its maximum value, with all the live points having similar likelihood values, as @fig-nested-sampling-termination shows.

```{python}
#| label: fig-nested-sampling-termination
#| fig-cap: An illustration of the conditions for termination in nested sampling.

import matplotlib.pyplot as plt
fig, axs = plt.subplots(nrows=2, ncols=1, sharex=True, gridspec_kw={'hspace': 0 }, figsize=(6, 3))
axs[1].plot(sampler.results.logvol, sampler.results.logl)
axs[1].set_ylim(-10, sampler.results.logl[-1]+2)
axs[1].set_xlabel('Prior volume compression $\log X$')
axs[1].set_ylabel('$\log \mathcal{L}$')
axs[1].set_xlim(*reversed(axs[1].get_xlim()))

axs[0].plot(sampler.results.logvol, sampler.results.logz)
axs[0].set_ylim(-10, np.max(sampler.results.logz)+2)
axs[0].set_ylabel('$\log \mathcal{Z}$')

for ax in axs:
	x0, x1 = -10, ax.get_xlim()[1]
	y0, y1 = ax.get_ylim()
	ax.fill(
		(x0, x0, x1, x1), 
		(y0, y1, y1, y0), 
		c='grey', 
		alpha=.1
	)
axs[0].arrow(-10, -2.5, -3, 0, width=.1, color='black')
_ = axs[0].text(-10.5, -6, 'Little contribution\nto the integral')
```


Thus, we can find a termination condition by diagnosing whether this is happening: for example, we can compute the contribution to the evidence integral from the current live points, and stop iterating when that becomes smaller than a given threshold --- this is the default in `dynesty` [@speagleDYNESTYDynamicNested2020].

Since this is a stochastic algorithm, there is always a chance we are making a mistake when terminating: for example, there could be a region with very low volume but high likelihood that none of the live points have happened upon, but which could give a significant contribution to the evidence.
There is no general solution to this issue, besides increasing the number of live points in order to improve the chances that some of them will happen upon the high-likelihood region. 

### Acceleration

The information gain provides an estimate of the expected volumetric compression: we expect to be sampling from the bulk of the posterior mass when $\log X \sim -H$, which will take approximately $n_\text{live}H \pm \sqrt{ n_\text{live}H }$ iterations due to Poisson variability.

If $n_\text{live}H$ is large, we expect the dominant source of uncertainty to be the one on the compression reached  at that stage --- it will be much larger than the uncertainty on the compression in the $\mathcal{O}(\sqrt{ n_\text{live}H })$ iterations required to traverse the posterior mass.
This leads us to the estimate
$$
\mathtt{std}(\log Z) \approx \sqrt{ \frac{H}{n_\text{live}} } \,.
$$

So, for a fixed variance on the evidence, we need to have $n_\text{live} \propto H$; therefore, the number of iterations is approximately $n_\text{iter} \propto n_\text{live}H \propto H^{2}$. 

The time complexity for nested sampling can then be estimated as

$$
T \approx n_{\text{live}} \times \langle t_{\text{like}} \rangle \times \langle n_{\text{replace}}\rangle \times  H 
$$

where

- $n_\text{live}$ is the number of live points used;
- $\langle t_{\text{like}} \rangle$ is the average likelihood evaluation time;
- $\langle n_\text{replace} \rangle$ is the average number of likelihood evaluations required to find a replacement for each dead point;
- $H$ is the information gain between posterior and prior.

This equation assumes that likelihood evaluation is the primary computational requirement; this may not always be the case, especially for sophisticated proposal methods such as machine-learning based ones [@williamsNestedSamplingNormalising2021].

Based on this equation, we can think of several ways to accelerate sampling;  @rouletInferringBinaryProperties2024 have reviewed many of them in the context of gravitational wave parameter estimation.

The minimum number of live points required for unbiased inference is generally fixed by the problem, though as we discuss in @sec-dynamic-nested-sampling it may be varied during the run to gain in performance.

A large gain can be often obtained by improving the replacement efficiency of the method used --- see also @sec-ns-sampling-options.
Accelerating the evaluation of the likelihood, $\langle t_\text{like} \rangle$, will also result in a direct reduction of computational time. In @sec-likelihood-acceleration we discuss some approaches in this direction.

#### Varying the number of live points {#sec-dynamic-nested-sampling}

The original nested sampling algorithm evolves a fixed number of live points throughout the run. 
It has since been proposed that it can be more efficient to vary it (@higsonDynamicNestedSampling2019, @speagleDYNESTYDynamicNested2020), depending on what is the quantity we are more interested in evaluating.

A nested sampling run gives us estimates for both the evidence and the posterior. If what we are most interested in is precisely computing the evidence, we should allocate more points in the early stages of compression, even though the posterior mass is very low there: this will give us better statistics on the active volume when we reach the posterior bulk.

If we are more interested in the posterior, on the other hand, we can do the initial compression with fewer points and use more once we reach the posterior bulk. 

It turns out [@higsonDynamicNestedSampling2019] that, while both these objectives can be optimized independently, the standard choice of using a constant number of live points is not on the Pareto front for the uncertainties on evidence and posterior: a balanced dynamical allocation of points can improve both compared to the constant case.

