## Inference and model comparison {#sec-inference-model-comparison}

This section contains the basic aspects of Bayesian parameter estimation,
the backbone of all gravitational wave data analysis.
This theory is of general validity, and it does not require us to 
restrict ourselves to the gravitational wave application quite yet.

When performing the analysis of some data $d$ according to some model $M$ parameterized by a finite number of parameters $\theta$, we employ Bayes' theorem, which is derived by expressing the joint probability $\text{prob}(d, \theta | M)$ in two different ways, making use of the identity $\text{prob}(a, b) = \text{prob}(a|b)\text{prob}(b)$: 

$$ \text{prob}(d, \theta | M) = \mathcal{L}(d | \theta, M) \pi (\theta | M) = p(\theta | d, M) \mathcal{Z}(d | M)\,.
$${#eq-bayes-theorem} 

The entries in this equation are: 

- the _likelihood_ $\mathcal{L}$ of the data given the model and a specific choice of its parameters --- it is a probability distribution over the data (i.e. $\int \mathcal{L}(d|\theta, M) \text{d}d = 1$), but we interpret it as a function of the parameters $\theta$, since the data we observed are fixed;
- the _prior_ $\pi$ --- a representation of our beliefs about the model's parameters before seeing the data, it is a probability distribution over the parameters;
- the _posterior_ $p$ for the model's parameters --- a representation of our updated beliefs about them after seeing the data, it is a probability distribution over the parameters;
- the _evidence_ $\mathcal{Z}$ for the model --- a normalization constant for the posterior, or the likelihood for the data marginalized over all the model's parameters.

An explicit formulation of the likelihood and prior is generally part of the problem definition, and can often be readily computed at any given value of the parameters.^[This is not true for all approaches: in Simulation-Based Inference (SBI, see @sec-simulation-based-inference) the likelihood may be implicitly defined; nevertheless, Bayes' theorem underlies those analyses as well.]

If the parameter space is high-dimensional, evaluating the posterior on a grid quickly becomes unpractical. 
A common solution to this issue is to use stochastic methods, which allow us to obtain a set of samples $\theta _i$ distributed according to the posterior and from which we can obtain information as discussed in @sec-posterior-samples.

There exist many different such algorithms. Several of them can probe the posterior distribution $p(\theta|d, M) \propto \mathcal{L}(d|\theta, M) \pi(\theta|M)$ without computing its normalization constant $\mathcal{Z}$, the evidence: for example, the Metropolis-Hastings algorithm, a flavor of Markov-Chain Monte Carlo [@hoggDataAnalysisRecipes2018], operates by accepting or rejecting proposals based on the ratio of their probabilities, which is normalization-independent.
Nested Sampling, which we shall discuss in more detail in @sec-nested-sampling, was developed as a method for computing the evidence, but it also yields the posterior as a by-product.
Machine learning-based methods such as Simulation-Based Inference (@sec-simulation-based-inference) can perform this task even faster.

### Posterior samples {#sec-posterior-samples}

What we refer to as "computing the posterior" means obtaining a useful representation for it.
For example, we are often interested in the _marginal distributions_ of single parameters. 
The marginal posterior for the parameter $\theta_{i}$ is defined by integrating over all the other parameters, _i.e._ _marginalizing_: 
$$
p(\theta_{i}|d) = \int \left( \prod_{k\neq i} \text{d}\theta_{k} \right) p(\theta| d)\,.
$$
The marginal distribution over two or more parameters can be defined analogously, by integrating along all dimensions except for the ones at hand.
Marginal distributions are the best approximation for what our posterior belief about the given parameter(s) should be; they include all the uncertainty on that parameter driven by the uncertainty in other, related parameters. @fig-marginalizing-vs-conditioning illustrates this by comparing the marginal distribution to the _conditional_ distribution, obtained by fixing the values of the other parameters to some value: 
$$
p(\theta_{i}|d, \left\{ \theta_{k}^{0} \right\}_{k \neq i})
=
p(\theta|d) \text{ computed at } \left\{ \theta_{k} = \theta_{k}^{0} \right\}_{k \neq i}
\,.
$$

Conditional distributions typically have less variance than their respective marginals, but unless we have a reason (such as a different observation) to specifically choose a given value for the other parameters, they are inaccessible in real parameter estimation.

```{python}
#| label: fig-marginalizing-vs-conditioning
#| fig-cap: "An illustration of the difference between marginalizing and conditioning for a multivariate Gaussian distribution."

from thesis_scripts.multivariate_normal import MultivariateNormal
n = MultivariateNormal([0, 0], [[1, 0.8], [0.8, 1]])
n.plot_2d_analytical(0, 0, .9)
```

A set of $N$ samples^[We represent these samples with two indices: a lower one indicating the dimension in the parameter space, and an upper one in parenthesis indicating the number of the sample.] $\left\{ \theta_i^{(k)} \right\}_{k}$ can be used to represent a high-dimensional posterior distribution. 
This is convenient, since marginal distributions are trivially obtained from these by only considering one of their entries, since $\left\{ \theta_{i}^{(k)} \right\} \sim p(\theta_{i}|d)$.

We can easily compute a number of summary statistics from samples, such as the expectation value of any function $f(\theta)$ [@thraneIntroductionBayesianInference2019]:

$$ \langle f \rangle_{\theta \sim p(\theta | d, M)} \approx \frac{1}{N} \sum _{k=1}^N f(\theta^{(k)}) \,.
$$

This general expression can be used for many different applications:

- the mean and variance of a parameter $\theta_{i}$ can be obtained by setting $f=\theta_{i}$ and $f= (\theta_{i} - \langle \theta_{i} \rangle)^{2} N/ (N-1)$ respectively;
- the covariance matrix of the whole parameter space can be obtained by setting $f = (\theta_{i}-\langle \theta_{i} \rangle)(\theta_{j} - \langle \theta_{j} \rangle) N/(N-1)$;
- a histogram for the parameter $\theta_{i}$ can be obtained with a set of functions which return the height of bin $m$: $f_{m} = [ \theta^{\text{min}}_{m} \leq \theta_{i}^{(k)} < \theta^{\text{max}}_{m}]$,^[This expression is using the Iverson bracket [@knuthTwoNotesNotation1992] which returns 1 if the statement inside is true and 0 otherwise.].

Working with samples also has disadvantages. 
For example, conditional distributions, which we are sometimes interested in, are difficult to obtain. 
Furthermore, in certain applications an estimate of the underlying density function is necessary. 
Techniques to obtain it exist, including Kernel Density Estimation and normalizing flows (@sec-normalizing-flows),
but they are not closed-form computations and often require tuning.

#### Credible regions {#sec-credible-regions}

A common method to quantify the uncertainty in the estimate of a parameter is to compute some kind of Bayesian Credible Interval with a given confidence $X$; in the gravitational wave literature, $X=0.9$ is generally the choice. 

There are different ways to define such an interval, depending on the problem at hand. 
If a parameter is bounded, and its posterior exhibits significant mass near the boundary, a single-sided interval is often given:
$$
\text{``}\theta_{i} \leq y \text{ at $X$ confidence"} \iff \int_{\theta_{i}^{\text{min}}}^{y} p(\theta_{i}|d) \text{d}\theta_{i} = X
$$
$$
\text{``}\theta_{i} \geq y \text{ at $X$ confidence"} \iff 
\int_y^{\theta_{i}^{\text{max}}} p(\theta_{i}|d) \text{d}\theta_{i} = X\,.
$$

If a parameter is not constrained near a boundary, a symmetric interval can be used:
$$
\text{``}\theta_{i}\in[y_{1}, y_{2}] \text{ at $X$ confidence, symmetric''}
\iff
\int_{y_{1}}^{y_{2}} p(\theta_{i}|d) \text{d}\theta_{i} = X\,,
$$
with also
$$
\int_{y_{2}}^{\theta_{i}^{\text{max}}} p(\theta_{i}|d) \text{d}\theta_{i} =
\int_{\theta_{i}^{\text{min}}}^{y_{1}} p(\theta_{i}|d) \text{d}\theta_{i} 
= \frac{1-X}{2}\,.
$$
These intervals are commonly adopted due to the ease of their computation, which reduces to computing quantiles of the $p(\theta_{i}|d)$ distribution, either at $X$ or $1-X$ (for the one-sided case) or at $(1-X) / 2$ and $(1+X) / 2$ (for the symmetric case).

Another method to quantify the uncertainty on one or more parameters is the _Highest Probability Density_ (HPD) region.
This is a region defined as $R(X) = \left\{ \theta | p(\theta|d) \geq K(X) \right\}$, where the value of $K$ is chosen such that 

$$
\int_{R(X)} p(\theta|d) \text{d}\theta = X\,.
$$

For a univariate and unimodal distribution, this is the shortest possible interval which contains a probability mass $X$, and it can be computed quickly by sorting the samples, computing all possible interval widths and choosing the minimum.

However, this technique will fail with no warning if the posterior distribution is not unimodal, 
since then the HPD may consist of disjoint intervals.
A computationally expensive, but more accurate way to estimate this region is: 

- discretizing the parameter space for the variables of interest into bins;
- estimating the probability density in each bin (this is often performed with a KDE, since counting the samples in each bin is affected by high variance); 
- sorting the bins by contained probability mass (highest first);
- adding the probability mass in the first $n$ bins, and increasing $n$ until the total surpasses $X$.

The $n$ bins obtained will represent the desired region.

#### Weighted samples {#sec-weighted-samples}

Some algorithms, such as Nested Sampling (@sec-nested-sampling) or importance-sampled Neural Posterior Estimation (@sec-importance-sampling-npe), can return a set of _weighted_ samples. 
This means that each sample $\theta_{i}$ is associated with a weight $w_{i}$.
Weighted samples can also arise in the context of _reweighting_: slightly perturbing the assumptions underlying an analysis and thus obtaining a set of weights in the form
$$
w_{i} = \frac{\mathcal{L}_{1}(\theta_{i}|d) \pi_{1}(\theta_{i})}{\mathcal{L}_{2}(\theta_{i}|d) \pi_{2}(\theta_{i})}\,.
$$

Summary statistics can be computed through __importance sampling__, as 
$$ \langle f \rangle_{\theta \sim p(\theta | d, M)} \approx \frac{\sum _{i=1}^N w_{i} f(\theta _i)}{\sum_{i=1}^{N}w_{i}} \,.
$$
Based on this, all the quantities that could be obtained as described in @sec-posterior-samples can be retrieved with weighted samples as well.

We can also extract equally-weighted samples from weighted ones by __rejection sampling__ [see _e.g._ @ashtonReconstructingResamplingGuide2025 for a review]:

1. Establish the highest weight, $w _\text{max} = \max w_{i}$;
2. for each sample $\theta_{i}$: 
	1. compute $x= w_{i} / w _\text{max} \in [0, 1)$;
	2. extract a uniformly random number $r \in [0, 1)$;
	3. if $r<x$, keep the sample $\theta_{i}$, otherwise, remove it.

On average, this procedure will retain $n\langle w \rangle / \max w$ out of $n$ samples; if many of the weights are lower than their maximum, it can become quite inefficient. 
In fact, under the realistic assumption of the weights being log-normally distributed, it can be shown that working with all weighted samples can be significantly more efficient than performing rejection sampling and then working with the resulting equally-weighted samples [@ashtonReconstructingResamplingGuide2025, fig. 3].

### $p$-$p$ tests {#sec-pp-plot}

Mistrusting the results of our analysis pipelines is wise: we ought to put them through as many tests as possible in order to spot any issues. 
A common test for self-consistency is the $p$-$p$ plot, which specifically regards the marginal distributions, $p(\theta_i | d)$ for a fixed $i$. 

This test starts with a campaign of injections, for which the true value $\hat{\theta_{i}}$ is known: every time, we need to generate a realistic simulation of the data $d$ and analyze it, feigning ignorance of the true value. 
Then, we may compute the percentile of the distribution at which the true value lies:
$$
u = \int_{-\infty}^{\hat{\theta}_{i}} p(\theta_{i}| d) \text{d}\theta = \text{CDF}_{p(\theta_{i}| d)}(\hat{\theta}_{i})\,.
$$
Here we assume for simplicity that the parameter can range over $\mathbb{R}$, but the same calculation can be performed starting integration from the lower bound.
This is the definition of the cumulative distribution function, computed at $\hat{\theta}_{i}$. 
Repeating this procedure $N_\text{inj}$ times, we will get a set of values $u_{j}$, where the index $j$ denotes the number of the injection.
If our analysis is self-consistent, and $p(\theta_{i}|d)$ is the probability density for the true value, then the $u_{j}$ should be uniformly distributed in the interval $[0, 1]$.

There are a few ways to check whether this is the case, both visual and statistical. 
The simplest is probably to create a histogram of the $u_{j}$ and visually check for uniformity. This is not a very powerful method, however, since it is hard to tell by eye which level of fluctuation is "acceptable", and there is a dependence on the size of the bins used for the histogram.
A better choice is to compute the empirical cumulative distribution function: 
$$
P_{\text{emp}}(u) = \frac{\text{number of }u_{j} \leq u}{N_\text{inj}}
$$

This is a "stepwise", locally constant function. For a perfectly uniform distribution, and an asymptotically high number of injections, it asymptotically tends toward $P(u) = u$. 
It is uniquely defined, with no parameters.

A first visual test is to plot it and check that it approximately follows the diagonal.
A useful variant of this is to plot $u$ on the horizontal axis and $P(u) - u$ on the vertical, which is expected to be near zero; see e.g. the work of @chatziioannouNoiseSpectralEstimation2019.
This allows for the resolution of small fluctuations from the diagonal. 

In order to help in the visual check, we need something to compare against: the magnitude of the expected fluctuations of $P(u)$ under the null hypothesis, i.e. if the distribution is indeed uniform.
If we fix a value of $u$, this can be reframed as counting, out of $N_\text{inj}$ independent and identically distributed draws from the distribution $\mathcal{U}([0, 1])$, how many are smaller than $u$.
The probability for each of them being smaller than $u$ is $u$ itself, so the probability mass function describing this scenario will be binomial, but scaled by $N_\text{inj}$:
$$
p  \left( P (u) = \frac{k}{N_\text{inj}} \right) = {k\choose N_\text{inj}} u^{k} (1-u)^{N _\text{inj}-k}
$$

Therefore we can easily compute its mean and variance: $\langle P(u) \rangle =u$ and
$$
\langle (P(u) -u)^{2} \rangle = \frac{u(1-u)}{N_\text{inj}}\,.
$$


```{python}
#| label: fig-pp-plot-theory
#| fig-cap: "Visualizations for a p-p test: histogram, empirical cdf, tilted empirical cdf. We also visualize the two modes of the Kolmogorov-Smirnov test. This plot was inspired by the visualizations in @williamsNestedSamplingNormalising2021."

from thesis_scripts import pp_plot
import numpy as np
from thesis_scripts import plt

rng = np.random.default_rng(seed=1)
u = rng.uniform(size=1000)

fig, ax = pp_plot.pp_plot(u, confidence_intervals=(.68, .95, .997))
plt.show()
```

Along with the visual tests, we can perform a Kolmogorov-Smirnov test, 
which can give us a $p$-value computed under the null hypothesis of the distribution being uniform.

In @fig-pp-plot-theory we show these for the one-sided Kolmogorov-Smirnov [@kolmogorovSullaDeterminazioneEmpirica1933;@smirnovTableEstimatingGoodness1948] statistics $D_{+}$ and $D_-$, defined in terms of the empirical CDF as

$$
D_{\pm} = \sup_{u} \left[ \pm \left( P_{\text{emp}}(u) - u \right)  \right]\,.
$$

We will always have $D_{\pm}\geq {0}$, since by definition $P _\text{emp}(0)= 0$, meaning that the set of values we are taking the $\text{sup}$ of includes 0. 
One may also use the two-sided statistic
$$
D = \sup_{u} \lvert  P_{\text{emp}}(u) - u  \rvert\,.
$$

We show both one-sided tests as opposed to the two-sided one, since their values can be used together to distinguish different types of misspecification, as we illustrate in @sec-pp-test-failure-modes. 
The density function of the K-S statistics under the null hypothesis is shown in @fig-kolmogorov-smirnov-distribution. 
The densities for the $D_{\pm}$ functions are identical - the transformation $u \to 1-u$ maps one to the other, and the null hypothesis is invariant under this reflection.
The scenario $D \approx 0$ is unlikely, as it would require the draws to precisely align themselves in an equally spaced pattern. On the other hand, $D_{\pm}$ being close to zero is plausible, as it only requires the realization to mostly be above or below the uniform CDF.

```{python}
#| label: fig-kolmogorov-smirnov-distribution
#| fig-cap: "Distribution for the K-S statistics."

import numpy as np
from thesis_scripts import plt
from scipy import stats

plt.figure(figsize=(6, 2.5))

D = np.linspace(0, 0.07, num=500)
n = 1000
plt.plot(D, stats.ksone.pdf(D, n=n), label=f'$D_{{\pm}}$ distribution for $n={{{n}}}$')
plt.plot(D, stats.kstwo.pdf(D, n=n), label=f'$D$ distribution for $n={{{n}}}$')

plt.legend()
plt.ylim(0, 65)
plt.xlabel('$D$ or $D_{\pm}$')
plt.ylabel('Probability density')
plt.show()
```

These tests are common in the literature: they were performed, for example, for the software `BILBY` [@romero-shawBayesianInferenceCompact2020]. 
More details on them can also be found in @romero-shawWhenModelsFail2022.
Within the sampler `nessai` [@williamsNestedSamplingNormalising2021], a $p$-$p$ plot test is applied to the insertion indices of new nested samples, _i.e._ the index of the new sample when ranking all previous live points by likelihood. As we shall discuss in @sec-nested-sampling, the new sample should be drawn uniformly in the likelihood-constrained prior mass. If this is the case, and the previous samples are also uniform in the variable $X$ (which denotes prior mass), then this insertion index should be uniformly distributed between $0$ and $n _\text{live}$, which can be investigated with a $p$-$p$ plot.
Note that in that case, overconstraining of the distribution being sampled will not correspond to overconstraining in terms of _insertion indices_, but instead be equivalent to an underestimation bias, with more quantiles near the top-end of the distribution.^[Also note that the nessai diagnostic plots are set up to show a quantity defined with an opposite sign compared to this work, equivalent to the difference $u - P(u)$.]

### $p$-$p$ test failure modes {#sec-pp-test-failure-modes}

Let us now explore the way that $p$-$p$ plots look when the test fails. 
We will keep the distribution according to which the true parameter $\hat{\theta}$ is distributed fixed to the standard normal, centered on zero and with unit variance, and we will explore how the $p$-$p$ plot can help us diagnose errors in the estimated posterior distribution.

First, let us suppose we have a bias in our measurement, so that the posterior distribution is not centered at the true value, 0, but instead at a slightly higher one, say 0.2. We will consider a simple Gaussian model, so that
$$
\begin{aligned}
p(\theta|d) &= \mathcal{N}(\theta; \mu=0.2, \sigma=1)\\
p(\hat{\theta}|d) &= \mathcal{N}(\theta; \mu=0, \sigma=1)\,.
\end{aligned}
$$

The result is in @fig-pp-plot-bias-positive.

```{python}
#| label: fig-pp-plot-bias-positive
#| fig-cap: "p-p plot in the scenario of an overestimation bias."

from thesis_scripts import pp_plot
import numpy as np
from thesis_scripts import plt
from scipy import stats

rng = np.random.default_rng(seed=1)
u = stats.norm(loc=0.2, scale=1).cdf(rng.normal(size=2000))

fig, ax = pp_plot.pp_plot(u, confidence_intervals=(.68, .95, .997))
plt.show()
```

@fig-pp-plot-bias-negative shows what happens if the bias is in the negative direction:
$$
\begin{aligned}
p(\theta|d) &= \mathcal{N}(\theta; \mu=-0.2, \sigma=1)\\
p(\hat{\theta}|d) &= \mathcal{N}(\theta;\mu=0, \sigma=1)\,.
\end{aligned}
$$

```{python}
#| label: fig-pp-plot-bias-negative
#| fig-cap: "p-p plot in the scenario of an underestimation bias."

from thesis_scripts import pp_plot
import numpy as np
from thesis_scripts import plt
from scipy import stats

rng = np.random.default_rng(seed=1)
u = stats.norm(loc=-0.2, scale=1).cdf(rng.normal(size=2000))

fig, ax = pp_plot.pp_plot(u, confidence_intervals=(.68, .95, .997))
plt.show()
```

Note that only one of the one-sided KS tests gives extreme results in either case. 

Now let us consider a different scenario: when the mean of the posterior distribution is correctly estimated, but its variance is not. 
If the variance is too high, we are _underconstraining_ the parameter, assigning a higher uncertainty to our measurement than is warranted: for example, if
$$
\begin{aligned}
p(\theta|d) &= \mathcal{N}(\mu=0, \sigma=1.2)\\
p(\hat{\theta}|d) &= \mathcal{N}(\mu=0, \sigma=1)\,.
\end{aligned}
$$

```{python}
#| label: fig-pp-plot-bias-underconstrain
#| fig-cap: "p-p plot in the scenario of an underconstraining bias."

from thesis_scripts import pp_plot
import numpy as np
from thesis_scripts import plt
from scipy import stats

rng = np.random.default_rng(seed=1)

u = stats.norm(loc=0, scale=1.2).cdf(rng.normal(size=2500))

fig, ax = pp_plot.pp_plot(u, confidence_intervals=(.68, .95, .997))
plt.show()
```

@fig-pp-plot-bias-underconstrain shows the result. 
In the opposite scenario, we are _overconstraining_ (@fig-pp-plot-bias-overconstrain), assigning a lower uncertainty to our measurement than is warranted: for example,
$$
\begin{aligned}
p(\theta|d) &= \mathcal{N}(\mu=0, \sigma=0.8)\\
p(\hat{\theta}|d) &= \mathcal{N}(\mu=0, \sigma=1)\,.
\end{aligned}
$$
```{python}
#| label: fig-pp-plot-bias-overconstrain
#| fig-cap: "p-p plot in the scenario of an overconstraining bias."

from thesis_scripts import pp_plot
import numpy as np
from thesis_scripts import plt
from scipy import stats

rng = np.random.default_rng(seed=1)

u = stats.norm(loc=0, scale=0.8).cdf(rng.normal(size=2500))

fig, ax = pp_plot.pp_plot(u, confidence_intervals=(.68, .95, .997))
plt.show()
```

Finally, let us consider a distribution with the correct mean and variance, but the wrong shape.
To this end we choose a generalized normal distribution, with a shape parameter $\beta = 2.5$. 
The $\beta = 2$ case recovers the standard normal distribution. 

```{python}
#| label: fig-generalized-normal
#| fig-cap: "Generalized normal and normal distributions with the same variance and mean."

import numpy as np
from thesis_scripts import plt
from scipy import stats

beta = 2.5
var = stats.gennorm.stats(beta, moments='v')
plt.figure(figsize=(6, 2.5))

dist = stats.gennorm(beta=beta, loc=0, scale=1/np.sqrt(var))
vals = np.linspace(-4., 6., num=1000)
plt.plot(vals, stats.norm(loc=0, scale=1).pdf(vals), label='Standard normal')
plt.plot(vals, dist.pdf(vals), label=f'Generalized normal with $\\beta={beta}$')
plt.ylim(0,0.5)
plt.xlim(vals[0], vals[-1])
plt.legend()
plt.xlabel('$\\theta$')
plt.ylabel('$p(\\theta)$')
plt.show()
```

We rescale the distribution so that it has unit variance, as shown in figure @fig-generalized-normal.
As this shift is harder to detect than the ones before, we need to raise the statistics. 

```{python}
#| label: fig-pp-plot-bias-distributional
#| fig-cap: "p-p plot in the scenario of the wrong distribution, despite correct mean and variance."

from thesis_scripts import pp_plot
import numpy as np
from thesis_scripts import plt
from scipy import stats

rng = np.random.default_rng(seed=1)

u = dist.cdf(rng.normal(size=10000))

fig, ax = pp_plot.pp_plot(u, confidence_intervals=(.68, .95, .997))
plt.show()
```

The distribution looks similar to the underconstrained case, as for the bulk of the probability mass (-2 to +2 in  @fig-generalized-normal) the difference between these distribution is analogous to underconstraining. 
However, close to the edges in @fig-pp-plot-bias-distributional we can see the trend reverse. 

### Model comparison {#sec-model-comparison}

The evidence $\mathcal{Z}$ is helpful when comparing models. 
In a realistic scenario, our model $M$ may not adequately capture the behavior of the system at hand,
but in @eq-bayes-theorem, all the terms are conditional on it: 
an analysis performed under the assumption that the model is true cannot 
inform us on its validity, by construction.
If more than one model is available, we can make some steps toward 
addressing this problem by comparing them; still, we should remember that 
our results are dependent on the set of models we used, and it is possible they may 
_all_ miss some important aspect.

We can write an anologous expression to @eq-bayes-theorem for both models $M_{1}$ and $M_{2}$:
$$
p(M_{i}|d) p(d) = p(d| M_{i}) p(M_{i});
$$
dividing one by the other, we get the following:
$$ 
\frac{p(M_{1} | d)}{p(M_{2}|d)} = \frac{p(d|M_{1})}{p(d|M_{2})} \frac{p(M_{1})}{p(M_{2})}.
$${#eq-model-comparison}

The left-hand term in @eq-model-comparison is dubbed _posterior odds_: 
it describes the degree to which we should prefer model $1$ over model $2$ after seeing the data $d$. On the right hand we have a product of two terms: the _Bayes Factor_ (BF)
$$
\text{BF}_{2}^{1} = \frac{p(d|M_{1})}{p(d|M_{2})}
$${#eq-bayes-factor}
describes the degree to which the data prefer model $1$ over model 2.
The remaining term, $p(M_{1}) / p(M_{2})$, is called _prior odds_, and it describes the degree to which we preferred model 1 over model 2 before seeing the data $d$.
This may be informed, for example, by previous observations, theoretical considerations, or simply be set to 1 if our belief is that both models are equally likely.

::: {#nte-odds-logits .callout-note collapse="true"}
##### On the usage of odds

@eq-bayes-factor can be applied several times in a row, as more observations become available; the Bayes Factors from each observation multiply. 

This has an interesting consequence if the two models at hand are complementary, i.e. one being correct excludes the other, and one or the other must be correct, so that their probabilities satisfy $p(M_{1})+p(M_{2})=1$. If this is the case, we may simplify the notation by simply using $P(M_{1})$ and $1-p(M_{1})=p(M_{2})$. 
Then, taking the logarithm of @eq-bayes-factor, we can express it as 
$$
\text{logit}(p(M_{1}|d)) = \log \text{BF}_{2}^{1} + \text{logit}(p(M_{1}))\,,
$$
where we defined the $\text{logit}$ function, also shown in figure @fig-logit-function:
$$
\text{logit}(p) = \log \frac{p}{1-p}\,.
$$

```{python}
#| label: fig-logit-function
#| fig-cap: "The logit function."

from thesis_scripts import *
import numpy as np
from thesis_scripts import plt

plt.figure(figsize=(6, 2.5))

p = np.linspace(5e-3, 1-5e-3, num=500)
plt.xlabel('$\\mathrm{{logit}}(p)$')
plt.ylim(0, 1)

plt.plot(np.log(p / (1-p)), p)
plt.xlabel('$\\mathrm{{logit}}(p)$')
plt.ylabel('$p$')
plt.grid()
plt.show()
```

The logit of a probability, $\text{logit}(p) \in \mathbb{R}$, is also called __log-odds__ 
can be argued to be more natural way to express it than $p\in (0, 1)$. 
Probabilities very close to 0 or 1 are extreme statements: in this parameterization, they are accordingly very far from the origin, and absolutes such as $p=0, 1$ are divergent towards $\pm \infty$.
:::

Based on this formalism, we may be tempted to multiply Bayes Factors 
from different observations of the same phenomenon. 
While this is correct in an idealized scenario, 
it can lead to dramatically incorrect conclusions when applied in practice,
due to its dependence on the prior used in each analysis;
@isiComparingBayesFactors2022 have discussed this 
in the context of tests of General Relativity (GR).

If two models are nested, _i.e._ one is a special case of the other, 
then we can express the Bayes Factor between them in a simple way
[@dickeyWeightedLikelihoodRatio1971;@cameronGeneralizedSavageDickeyRatio2013]:
$$
\text{BF}_{1}^{2} = \frac{p_{2}(\theta=\theta_{0}|d)}{\pi_{2}(\theta=\theta_{0})}\,.
$${#eq-savage-dickey-density-ratio}
Here, model 1 is the special case of model 2 in which parameter $\theta$ equals $\theta_{0}$, $p_{2}$ is the marginal posterior distribution for the parameter $\theta$ under model 2, while $\pi_{2}$ is the marginal prior distribution for the parameter $\theta$ under model 2.

The value of $\pi_2$ computed at any given point is sensitive to how wide the prior is, since it must be a normalized probability distribution. For example, the density of a uniform prior over an interval $A$ is precisely $1/A$.

This formulation illustrates the general fact that Bayes Factors are heavily dependent on the width of the prior distribution.
This is a well-known feature of Bayesian inference, known as the Occam Factor or Penalty.
Among two models which fit the data equally well (_i.e._ the maximum values of their likelihoods are equal),
the preferred one is the one for which the likelihood has high values for a larger fraction of the prior space.
Qualitatively, this penalizes flexible models, which are able to fit many different scenarios beside the observed one,
in favor of ones which only fit the observed scenario and few others.

A negative consequence of this arises if the prior distributions cannot be selected in a principled way, though: if they are set too wide, the data may seem to favor the baseline model even in the presence of a deviation.
Then, by the way Bayes Factors are constructed, if the BF for any single observation favors the baseline model, combining many of them from different observations only accumulates evidence against a deviation, even if a small deviation is present and could be detected by a simultaneous analysis of all events.