---
format:
    html:
        code-fold: true
        bibliography: ../../rehear.bib
    pdf:
        execute:
            echo: false
        bibliography: ../../rehear.bib
---

# Acceleration methods

{{< include sections/_ns-acceleration-methods.qmd >}}

{{< include sections/_nested-importance-sampling.qmd >}}

## Likelihood acceleration

The two terms we need to compute in the likelihood ratio [@eq-likelihood-ratio] are the following integrals

$$
\mathcal{L}_{hd} = \mathrm{Re}(h(\theta)| d) = 4 \mathrm{Re}\int_{0}^{f_\text{max}} \frac{h(f; \theta) d^*(f)}{S_{n}(f)} \text{d}f\,,
$$
and

$$
\mathcal{L}_{hh} = (h(\theta)| h(\theta)) = 4 \int_{0}^{f_\text{max}} \frac{|h(f; \theta)|^{2}}{S_{n}(f)} \text{d}f\,.
$$

These are integrals of oscillatory functions, so evaluating them as simple Riemann sums requires a large number of samples to achieve convergence.

### Relative binning

Relative binning [@zackayRelativeBinningFast2018] is a technique to accelerate the evaluation of the integrals in the likelihood.

The idea is that, while the waveform itself may be highly oscillatory, it will generally be close to a reference one.

The two terms are approximated as follows, in terms of a set of frequencies $b = \left\lbrace f_{i}\right\rbrace$:

$$
 \mathcal{L}_{hd} = \mathrm{Re} \sum_{b} (A_{0}(b) r_{0}^{*}(b) + A_{1}(b) r_{1}^{*} (b))
$$
and
$$
\mathcal{L}_{hh} = \sum_{b} ( B_{0}(b) |r_{0}(b)|^{2} + 2 B_{1}(b) \mathrm{Re}(r_{0}(b) r_{1}^{*}(b)))
$$
Here, the ratio $r(f) = h(f)  / h_{0}(f)$ of the generic waveform $h$ to the reference one $h_{0}$ is expressed to linear order in each bin:
$$
r(f) = r_{0}(b) + r_{1}(b) (f-f_{m}(b)),
$$
where $f_{m}(b)$ is the central frequency in the bin.
During likelihood evaluation we can easily compute a set of ratios $r(b)$ at every bin edge, and then we will have
$$
r_{0}(b) = \frac{r(b)+r(b+1)}{2}
\qquad \text{and} \qquad r_{1}(b) = \frac{r(b+1)-r(b)}{\text{d}f(b)}\,.
$$

Crucially, this depends on the ratio $r(f)$ being relatively smooth across the frequency axis.
This is expected to be approximately true for all the relevant points in the posterior, potentially not if we stray from its peak.

This formulation holds for the 22 mode, but it is possible to write a more generic one including higher order modes, at the expense of some more digital ink [@narolaRelativeBinningComplete2023].

For a look at how the waveform ratio looks in the LGWA case, see @fig-projected-lgwa-waveforms-ratio.

The authors of the original paper use a frequency axis obtained from first-principles arguments. However, it is also possible to run a greedy search to optimize it. @leslieModebymodeRelativeBinning2021 did it, by optimizing on a single waveform.
My attempt is in @sec-greedy-relbin-selection.

#### Greedy relative binning grid selection {#sec-greedy-relbin-selection}

In [@zackayRelativeBinningFast2018] they give a rough outline for the functional form of the relative binning loglikelihood errors:
$$
\Delta \log \mathcal{L} (\theta) \approx \beta \left( \log \mathcal{L}_\text{max} - \log \mathcal{L}(\theta) \right) 
$$

In principle, this with a fixed $\beta$ does not give big guarantees on how big the error will be.

##### Adaptive accuracy requirement

Suppose $\varepsilon(\theta)$ is the error in log-likelihood evaluation at point $\theta$.
The typical requirement, as asked for example in ROQ basis construction, is 
$$
\varepsilon(\theta) < \varepsilon_{0} \quad \forall \theta \in \Omega\,.
$$

But we can relax this: we can set
$$
\mathbb{E}_{p(\theta|d)}[\varepsilon] < \varepsilon_{0}\,.
$$

This can be achieved by a $\theta$-dependent requirement. For example, if we set
$$
\varepsilon(\theta) \leq \frac{C}{L(d|\theta)\pi(\theta)}
$$
then the expectation value reads
$$
\mathbb{E}_{p(\theta|d)}[\varepsilon]
\leq \int \frac{C}{L(d|\theta)\pi(\theta)} p(\theta|d) \text{d}\theta 
= \int \frac{C}{Z(d)} \text{d}\theta = \frac{C V_{\theta}}{Z(d)}
$$

Therefore, we need to set
$$
C = \varepsilon_{0} \frac{Z(d)}{V_{\theta}}\,.
$$

The quantity
$$
\frac{Z}{V_{\theta}} = \langle L(d|\theta) \pi(\theta) \rangle_{\mathcal{U}(\theta)} 
$$
can be estimated roughly at the beginning of inference, if we know $L_\text{max}$, I guess?
Is it related to the ratio between the posterior and prior volumes?

###### Gaussian example

Let us consider the problem of sampling the standard normal distribution, with a uniform prior constraint of $x \in [-10, 10]$. 
The integral is $Z \approx 1$, the prior volume is $V_{\theta}=20$. So, we should set $C = \varepsilon_{0} / 20$.

```{python}
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(-5, 5, num=1000)

def standard_normal(x):
    return -x**2/2 - np.log(np.sqrt(2*np.pi))

eps_0 = 1e-5
C = eps_0 / (x[-1]-x[0])

plt.semilogy(x, np.exp(standard_normal(x)), label='PDF')
plt.semilogy(x, C / np.exp(standard_normal(x)), label='accuracy constraint')
plt.axhline(eps_0, c='black', ls='--', label='$\\varepsilon_0$')
plt.legend()
```

We may want to set a minimum tolerable accuracy requirement, so that 
$$
\varepsilon(\theta) = \max\left( \varepsilon _\text{min}, \frac{C}{L(d|\theta)\pi(\theta)} \right)\,.
$$

How does that complicate things?
A sensible choice could be $\varepsilon _\text{min} = \varepsilon_{0} / 2$.

##### Ratio bounds

We want to be able to represent waveform ratios to a reference waveform with parameters $\theta_{0}$,
$$
r(f; \theta) = \frac{h(f; \theta)}{h(f, \theta_{0})}\,,
$$
with the fewest possible frequency grid points.
We do not need to do this for all points in the parameter space, but only for those which will have a large value of the posterior.

The problem is that we do not, _a priori_, know what that region is (it is the final result of our computation!).
So, the hope is to simultaneously run a search over the parameter space (not necessarily with the actual likelihood as the function being explored) and add frequency grid points as needed to decrease the representation error in the new points we are finding.

We can get a bound on our likelihood using $r$ only. Let us start with the "injection" loglikelihood ratio, with the noise set to zero:
$$
\log \mathcal{L} 
= - \frac{1}{2} \lVert h - h_{0} \rVert^{2}
= - \frac{1}{2} \lVert h_{0}(r-1) \rVert^{2} 
$$

By Jensen's inequality, we can apply the convex function $- \log$ inside and outside the norm, and get the following expression:
$$
\lVert -\log h_{0} - \log(r-1) \rVert \geq 
-\log \lVert h-h_{0} \rVert \,.
$$

::: {#nte-complex-logs .callout-warning collapse="true"}
##### On complex logs

Does Jensen's inequality still work if we consider logs of complex numbers? Maybe not...
This probably need to be handled by separating amplitude and phase.

Or actually - the phase doesn't matter, since we're taking the square norm!
It should be $\log \lvert r-1 \rvert$.

:::

Then, we can use the triangle inequality:
$$
\lVert -\log h_{0} - \log(r-1) \rVert
= \lVert \log h_{0} +\log(r-1) \rVert
\leq \lVert \log h_{0} \rVert + \lVert \log (r-1) \rVert 
$$

So we have our final result:
$$
\frac{1}{2} \lVert \log h_{0} \rVert + \frac{1}{2} \lVert \log (r-1) \rVert \geq -\log \sqrt{ -2 \log \mathcal{L} }
$$

It is then to be seen what we can do with this upper bound.
The norm of the ratio minus one is greater than some increasing function of the likelihood...  

For $h = h_0$ we get $\infty \geq \infty$...

### Reduced order quadrature

This technique differs from relative binning, in that it employs a greedy algorithm to sample from a given prior space and construct a basis that will represent all waveforms sampled there to within a given tolerance.

The equations are as follows:
$$
\mathcal{L}_{dh} \approx \sum_{j=1}^{N_{L}} h(f_{j}, \theta) \omega_{j}
$$
$$
\mathcal{L}_{hh} = \sum_{i=1}^{N_{Q}} \sum_{j=1}^{N_{Q}} h(f_{i}, \theta) h^{*}(f_{j}, \theta) \psi_{i}
$$

About basis size and storage details: [@morisakiRapidLocalizationInference2023]. 

Could we not avoid storing the full ROQ basis, if we proceed as follows?
- determine the sequence of "worst-represented" waveform parameters, $\theta_{i}$, at each iteration
	- the basis does not simply consist of the waveforms $h(\theta_{i})$, since the procedure also includes orthonormalization
- iterate through these parameters, constantly updating the subspace projector operator and  as you go
	- at each iteration, compute $h(\theta_{i})$
	- project it onto the orthogonal subspace using $\mathcal{P}_{i-1}$
	- compute the weights $\omega_{i}$ and $\psi_{i}$
	- update the projector to $\mathcal{P}_{i} = P_{i-1} + e_{i} e_{i}^{\top}$

Useful references:
- Antil+13 for the two-step ROQ basis construction

## Multimodality reduction

The folding algorithm from [@rouletRemovingDegeneracyMultimodality2022].

For LGWA the following symmetries will be preserved, I think:
$$
\phi \to \phi + \pi
$$
$$
\psi \to \psi + \frac{\pi}{2}
$$

also one with $\cos \iota$, but let's see.

Suppose we have a set of quasi-symmetries, denoted by a family of $2^{N}$ transformations $\sigma_{i}$ (the first is the identity). We consider a "folded subset" and only look there, computing the posterior probability of a point $\tilde{\theta}$ as
$$
\tilde{P} (\tilde{\theta}) = \sum_{i=1}^{2^{N}} P(\sigma_{i}(\tilde{\theta}))
$$
We do need to compute all the $2^{N}$ probabilities, and we should store them (or actually not, since we can recompute them for the relevant posterior samples...)

Then we run our sampler on the folded space, and get a posterior there. 
We can unfold it by taking each weighted sample $(\tilde{\theta}_{j}, w_{j})$ and splitting it into $2^{N}$ samples:
$$
\left(\sigma_{i}(\tilde{\theta}_{j}), \frac{w_{j} P(\sigma_{i}(\tilde{\theta}_{j}))}{\tilde{P}(\tilde{\theta})}\right)\,.
$$
These are in principle ratios of posteriors but in practice the prior is invariant under all the symmetries at hand.

The unfolding code by Roulet is [here](https://github.com/jroulet/cogwheel/blob/74c8dc3b122ebea5de99e9007997a0418e450e32/cogwheel/prior.py#L134).

## Analytic marginalization

If the exact dependence of the likelihood on a given parameter is known, 
the integral over said parameter can sometimes be performed analytically.

[@singerRapidBayesianPosition2016], [@thraneIntroductionBayesianInference2019]
[@LIGOT1300326v1AnalyticMarginalisation].

### Reference phase

A convenient parameter to marginalize over is the reference phase [@LIGOT1300326v1AnalyticMarginalisation]. 
It does not have any astrophysical significance, despite being crucial for a complete description of the signal.

If the waveform is dominated by the $\ell |m| = 22$ mode of emission, 
its dependence on the coalescence phase $\phi_c$ is simply $h(\phi_c, \theta) = h(\phi_c=0, \theta) e^{2 \mathrm{i} \phi_c}$. 
For convenience, we shall denote the waveform at a reference phase, $h(\phi_{c}=0, \theta)$, simply as $h(\theta)$.

Therefore, the marginalized likelihood reads 

$$ 
\begin{align}
\int_{0}^{2\pi} \mathcal{L}(d| \phi_{c}, \theta) \pi(\phi_{c}) \text{d}\phi_{c} &= \mathcal{Z}_{N} \exp\left(  - \frac{1}{2}(h(\theta) | h(\theta)) \right) \int_{0}^{2 \pi} \exp(\Re (d | h(\phi_{c}, \theta))) \pi (\phi_{c}) \text{d} \phi_{c} \\ \\
&= \mathcal{Z}_{N} \exp\left(  - \frac{1}{2}(h(\theta) | h(\theta)) \right) I_{0}(|(d|h(\theta))|)\,.
\end{align} 
$${#eq-phase-marginalized-likelihood}

The function $I_{0}$ appearing in the last expression is a modified Bessel function of the first kind, the solution to the following integral:
$$
I_{0}(\sqrt{ A^{2} + B^{2} }) = \frac{1}{2 \pi} \int_{0}^{2\pi} \exp(A \cos \phi + B\sin \phi) \text{d} \phi\,.
$$

#### Recovering phase from marginalized samples

Since the analytical likelihood is known, it is possible to sample the phase after having performed a run with a phase-marginalized likelihood [@thraneIntroductionBayesianInference2019]. 

For any given sample $\theta$ from a phase-marginalized posterior we can write the posterior as a function of $\phi_{c}$, conditioned on $\theta$: the integrand in equation @eq-phase-marginalized-likelihood. 

### Distance

