---
format:
    html:
        code-fold: true
        bibliography: ../../rehear.bib
    pdf:
        execute:
            echo: false
        bibliography: ../../rehear.bib
---
# Gravitational wave parameter estimation

## The Whittle likelihood

The likelihood expresses the answer to the question:

> How likely are we to have observed the data $d$, under the assumption that this data 
> can be decomposed as noise $n$ plus a signal $h(\theta)$ with fixed parameters $\theta$?

If we are writing the data as $d = n + h(\theta)$, this is equivalent to asking:

> How likely are we to observe a noise realization equal to $n = d - h(\theta)$?

In order to answer this, we need a model for the noise. 
In gravitational wave data analysis, it is commonly assumed that the noise
can be described as a stationary time series, $n(t)$, such that the autocovariance
$\mathbb{E}[n(t)n(t+\Delta t)] \equiv \gamma(\Delta t)$ can be expressed as a function of $\Delta t$ only [@edwardsBayesianSemiparametricPower2015, section II.C].
A further assumption made is that the noise has zero mean ($\mathbb{E}[n(t)] = 0$ for any time).

The Fourier transform of the autocovariance $\gamma(\Delta t)$ is called the Power Spectral Density, $S_{n}(f)$. 

With these ingredients, we can write the Whittle approximation to the Gaussian likelihood [@whittleCurvePeriodogramSmoothing1957], [@rouletInferringBinaryProperties2024]:

$$
\begin{aligned}
\log \mathcal{L}(n) &= \log \mathcal{N_{1}} + \sum_{m>0} \left[  \log \left(\frac{2}{\pi T S_{n}(f_{m})} \right) - \frac{2 |n(f_{m})|^{2}}{T S_{n}(f_{m})} \right]  \\
&= \log \mathcal{N_{2}} - \frac{1}{2} \int_{0}^{f_\text{max}} \frac{4 |n(f)|^{2}}{S_{n}(f)} \text{d}f\\
&= \log \mathcal{N_{2}} - \frac{1}{2} (n|n)\,.
\end{aligned}
$$

The normalization terms $\mathcal{N_{1}}$ and $\mathcal{N_{2}}$ are different, but crucially they only depend on the Power Spectral Density, not on the specific noise realization.

In the last equation, we introduced the notation $(\cdot | \cdot)$ for the noise-weighed inner product between waveforms, defined as 

$$ (a | b) = 4 \Re \int_0^\infty \frac{a(f) b^*(f)}{S_n(f)}\text{d}f \,.
$$

More specifically, this likelihood answers the question: 

> How likely is it that noise distributed according to the PSD $S_{n}(f)$ will have the specific realization $n$?

We can then consider two scenarios, depending on whether we fix the PSD or not.

### Fixed Power Spectral Density

In the data analysis for gravitational wave signals from ground-based interferometers, it is common practice to fix the PSD to an estimate obtained considering data near the event.
This is acceptable, since variations in the noise distribution happen on much slower time scales than duration of the signal itself [need citations for this!].

In such a case, we can rewrite the likelihood in terms of the signal $h(\theta) = d - n$ as follows:

$$
\begin{aligned}
\log \mathcal{L}(d | \theta) &= \log \mathcal{N_{2}} - \frac{1}{2} (d-h(\theta)| d- h(\theta)) \\
&= \log \mathcal{N_{2}} - \frac{1}{2} (d| d) + \mathrm{Re}(h(\theta)|d) - \frac{1}{2} (h(\theta)|h(\theta))\,.
\end{aligned}
$$

We can work around the messy normalization term [@rouletInferringBinaryProperties2024]. Our likelihood is written assuming that a signal is present in the data, but suppose that was not the case: then, we would have $d = n$ and therefore

$$
\log \mathcal{L}(d | \text{noise only}) = \log \mathcal{N_{2}} - \frac{1}{2} (d|d)\,.
$$

Since we are assuming the PSD is fixed, this model has zero parameters, and this likelihood can also be interpreted as an evidence: $\log \mathcal{L}(d | \text{noise only}) = Z _\text{noise}$.

Therefore, we can perform parameter estimation using as a "log-likelihood" the likelihood ratio

$$
\log \mathcal{L}_{r} (d|\theta) = \log \frac{\mathcal{L}(d|h(\theta))}{Z _\text{noise}} = \mathrm{Re}(h(\theta)| d) - \frac{1}{2} (h(\theta)| h(\theta))\,,
$$ {#eq-likelihood-ratio}

and the "evidence" we will obtain, i.e. the integral of $\mathcal{L}_{r}(d|\theta) \pi(\theta) \text{d}\theta$ over the parameter space, will actually be a Bayes Factor, $Z_\text{signal and model} / Z_\text{noise}$.

### Varied Power Spectral Density

TBD

## Matched filtering

When we measure gravitational wave data $d(t)$, we will have a contribution from noise $n(t)$ and signal
$h_\theta(t)$, where $\theta$ are the parameters: $d = n + h_\theta$.
We can estimate the parameters $\theta$ by exploring the posterior distribution 

$$ p(\theta | d) = \mathcal{L}(d | \theta ) \pi (\theta ) = \mathcal{N} \exp \left( (d | h_\theta) - \frac{1}{2} (h_\theta | h_\theta) \right) \pi (\theta )\,,
$$


while $\pi (\theta )$ is our prior distribution on the parameters.
This kind of analysis is assuming that the noise is Gaussian, and described by the power spectral density (PSD) $S_n(f)$.

This posterior, in full generality, is an arbitrary function
of more than a dozen parameters, making it somewhat difficult to calculate and interpret.
Typically, the algorithms used to compute it for real signals explore the parameter space in some stochastic manner, and yield a set of some thousands of samples $\lbrace\theta\rbrace_i$. 

This makes it simple to compute summary statistics like the average of a parameter 
$\langle \theta_i \rangle$, the variance $\sigma_i^2 = \langle (\theta_i- \langle \theta_i\rangle)^2 \rangle$, as 
well as covariances $\mathcal{C}_{ij} = \langle (\theta_i- \langle \theta_i\rangle) (\theta_j- \langle \theta_j\rangle) \rangle = \langle \Delta \theta^i \Delta \theta^j \rangle$.

At this stage, we are not making any approximation, and the 
covariance matrix is just a summary tool. 

These quantities give us an estimate of how well any given parameter is constrained, although
they do not tell the whole story especially in the regime where the error $\sigma$ starts to be comparable 
with the signal.
For those cases, in general, if the posterior is available the best idea is to plot it; 
this is typically done as a corner plot, which shows the correlations among different 
parameters.

## Signal-to-noise ratio

The signal-to-noise ratio (SNR) statistic $\rho$ for the data $d$, assuming a template $h$, is 
$\rho = (d | h) / \sqrt{(h|h)}$.
This is the quantity that matched-filter signal searches attempt to maximize. 
In general this will be given by $\rho = [(n|h) + (h|h)] / \sqrt{(h|h)}$, but if we are performing a forecast
we cannot know in advance what the noise realization will be. Fortunately, the average contribution
of the term $(n|h)$ is zero, so the expectation value is just $\rho \approx \sqrt{(h|h)}$. 

This does not mean that we are neglecting the noise, since its _distribution_ $S_n$ is still taken 
into account: for example, consider the behaviour under a global rescaling of the noise PSD: $\rho \propto 1 / \sqrt{S_n}$.
At each frequency $f$ the noise is normally distributed, with variance $S_n(f)$ and mean zero,
so we are just considering the mean value of the noise distribution. 

### SNR thresholds

If we were searching for a signal without any possible shift in time and with the certainty 
that the noise did not contain any glitches or non-Gaussianities, then the SNR would simply follow
a $\chi^2$ distribution with two degrees of freedom [@babakSearchingGravitationalWaves2013], 
meaning that we could reach "five $\sigma$" significance ($p$-value of $5.7\times 10^{-7}$) 
with a threshold of $\rho = 5.5$. 

This is not the case in real data, since both the aforementioned assumptions are false:
the different possible arrival times of a signal are effectively "more trials", but more importantly
the non-Gaussianity of the noise means that high-SNR triggers in a matched filtering search will
be much more common than simple Gaussian statistics would indicate.
Accounting for these factors is tricky, and in real data it is typically accomplished 
by performing time-slides: taking real detector data, but shifted across detectors by more than $t_{\text{min}} = d/c$, where $d$ is the maximum distance separating them.
In the assumption that signals are rare (which holds for current detectors, for ET 
this will have to be challenged), this allows us to generate arbitrary amounts of noise-only 
realistic data by removing all possible coincidences.
We can then compute the rate of noise instances surpassing our threshold, even if this rate
is very low.
With this, we can compute the false-alarm rate (FAR) associated to a given SNR threshold.
It should also be noted that real searches also include other vetoes, such as requiring
that each frequency band contributes appropriately to the SNR [@nitzRapidDetectionGravitational2018], which allows us to discard many loud glitches.

The scaling of the FAR as a function of SNR, in the absence of large outliers, is typically exponential [@lynchObservationalImplicationsLowering2018]:
$$ \text{FAR} = \text{FAR}_8 \exp \left( - \frac{\rho - 8}{\alpha}\right) \,.
$$

The specific values for the FAR at $\rho = 8$ and the scaling parameter $\alpha$ 
are found through a fit, and they depend on the signal template.
A fit of O1 data found $\alpha = 0.18$ and $\text{FAR}_8 = 5500 \text{yr}^{-1}$ for BBH, 
and $\alpha = 0.13$ and $\text{FAR}_8 = 30000 \text{yr}^{-1}$ for BNS.
This value of $\alpha$ means that the exponential cutoff is quite steep: 
for example, bringing the BNS FAR from 30 thousand per year to just one 
per year only requires us to raise the threshold to $\rho = 9.4$.

### Forecasting SNR

For the purposes of forecasting, then, what SNR threshold should we consider 
as the minimum for detectability?
We cannot know yet which glitches will affect our future detector, but 
we can safely say that a threshold in the range of 8 to 10 is probably 
acceptable.

This quantity is easy to estimate and not too dependent on the 
specifics of the waveform model: for one, it discards all phase information:

$$ \text{SNR} = 2 \sqrt{\int_0^\infty \frac{|h(f)|^2}{S_n(f)} \text{d}f}
$$

and also waveform models for compact binaries differ significantly only in the 
high-frequency region; for most of the inspiral the signal is decently
modelled by a simple powerlaw $h\propto f^{-7/6}$, therefore the overall
SNR integral is much more stable under changes of model than the parameter
estimation forecasts we will discuss later.

## Likelihood acceleration

The two terms we need to compute in the likelihood ratio [@eq-likelihood-ratio] are the following integrals

$$
\mathcal{L}_{hd} = \mathrm{Re}(h(\theta)| d) = 4 \mathrm{Re}\int_{0}^{f_\text{max}} \frac{h(f; \theta) d^*(f)}{S_{n}(f)} \text{d}f\,,
$$
and

$$
\mathcal{L}_{hh} = (h(\theta)| h(\theta)) = 4 \int_{0}^{f_\text{max}} \frac{|h(f; \theta)|^{2}}{S_{n}(f)} \text{d}f\,.
$$

These are integrals of oscillatory functions, so evaluating them as simple Riemann sums requires a large number of samples to achieve convergence.

### Relative binning

Relative binning [@zackayRelativeBinningFast2018] is a technique to accelerate the evaluation of the integrals in the likelihood.

The idea is that, while the waveform itself may be highly oscillatory, it will generally be close to a reference one.

The two terms are approximated as follows, in terms of a set of frequencies $b = \left\lbrace f_{i}\right\rbrace$:

$$
 \mathcal{L}_{hd} = \mathrm{Re} \sum_{b} (A_{0}(b) r_{0}^{*}(b) + A_{1}(b) r_{1}^{*} (b))
$$
and
$$
\mathcal{L}_{hh} = \sum_{b} ( B_{0}(b) |r_{0}(b)|^{2} + 2 B_{1}(b) \mathrm{Re}(r_{0}(b) r_{1}^{*}(b)))
$$
Here, the ratio $r(f) = h(f)  / h_{0}(f)$ of the generic waveform $h$ to the reference one $h_{0}$ is expressed to linear order in each bin:
$$
r(f) = r_{0}(b) + r_{1}(b) (f-f_{m}(b)),
$$
where $f_{m}(b)$ is the central frequency in the bin.
During likelihood evaluation we can easily compute a set of ratios $r(b)$ at every bin edge, and then we will have
$$
r_{0}(b) = \frac{r(b)+r(b+1)}{2}
\qquad \text{and} \qquad r_{1}(b) = \frac{r(b+1)-r(b)}{\text{d}f(b)}\,.
$$

Crucially, this depends on the ratio $r(f)$ being relatively smooth across the frequency axis.
This is expected to be approximately true for all the relevant points in the posterior, potentially not if we stray from its peak.

This formulation holds for the 22 mode, but it is possible to write a more generic one including higher order modes, at the expense of some more digital ink [@narolaRelativeBinningComplete2023].

For a look at how the waveform ratio looks in the LGWA case, see @fig-projected-lgwa-waveforms-ratio.

### Reduced order quadrature

This technique differs from relative binning, in that it employs a greedy algorithm to sample from a given prior space and construct a basis that will represent all waveforms sampled there to within a given tolerance.

The equations are as follows:
$$
\mathcal{L}_{dh} \approx \sum_{j=1}^{N_{L}} h(f_{j}, \theta) \omega_{j}
$$
$$
\mathcal{L}_{hh} = \sum_{i=1}^{N_{Q}} \sum_{j=1}^{N_{Q}} h(f_{i}, \theta) h^{*}(f_{j}, \theta) \psi_{i}
$$

About basis size and storage details: [@morisakiRapidLocalizationInference2023].


## Multimodality reduction

The folding algorithm from [@rouletRemovingDegeneracyMultimodality2022].

For LGWA the following symmetries will be preserved, I think:
$$
\phi \to \phi + \pi
$$
$$
\psi \to \psi + \frac{\pi}{2}
$$

also one with $\cos \iota$, but let's see.

Suppose we have a set of quasi-symmetries, denoted by a family of $2^{N}$ transformations $\sigma_{i}$ (the first is the identity). We consider a "folded subset" and only look there, computing the posterior probability of a point $\tilde{\theta}$ as
$$
\tilde{P} (\tilde{\theta}) = \sum_{i=1}^{2^{N}} P(\sigma_{i}(\tilde{\theta}))
$$
We do need to compute all the $2^{N}$ probabilities, and we should store them (or actually not, since we can recompute them for the relevant posterior samples...)

Then we run our sampler on the folded space, and get a posterior there. 
We can unfold it by taking each weighted sample $(\tilde{\theta}_{j}, w_{j})$ and splitting it into $2^{N}$ samples:
$$
\left(\sigma_{i}(\tilde{\theta}_{j}), \frac{w_{j} P(\sigma_{i}(\tilde{\theta}_{j}))}{\tilde{P}(\tilde{\theta})}\right)\,.
$$
These are in principle ratios of posteriors but in practice the prior is invariant under all the symmetries at hand.

The unfolding code by Roulet is [here](https://github.com/jroulet/cogwheel/blob/74c8dc3b122ebea5de99e9007997a0418e450e32/cogwheel/prior.py#L134).

## Analytic marginalization

If the exact dependence of the likelihood on a given parameter is known, 
the integral over said parameter can sometimes be performed analytically.

[@singerRapidBayesianPosition2016], [@thraneIntroductionBayesianInference2019]
[@LIGOT1300326v1AnalyticMarginalisation].

### Reference phase

A convenient parameter to marginalize over is the reference phase [@LIGOT1300326v1AnalyticMarginalisation]. 
It does not have any astrophysical significance, despite being crucial for a complete description of the signal.

If the waveform is dominated by the $\ell |m| = 22$ mode of emission, 
its dependence on the coalescence phase $\phi_c$ is simply $h(\phi_c, \theta) = h(\phi_c=0, \theta) e^{2 \mathrm{i} \phi_c}$. 
For convenience, we shall denote the waveform at a reference phase, $h(\phi_{c}=0, \theta)$, simply as $h(\theta)$.

Therefore, the marginalized likelihood reads 

$$ 
\begin{aligned}
\int_{0}^{2\pi} \mathcal{L}(d| \phi_{c}, \theta) \pi(\phi_{c}) \text{d}\phi_{c} &= \mathcal{Z}_{N} \exp\left(  - \frac{1}{2}(h(\theta) | h(\theta)) \right) \int_{0}^{2 \pi} \exp(\Re (d | h(\phi_{c}, \theta))) \pi (\phi_{c}) \text{d} \phi_{c} \\ \\
&= \mathcal{Z}_{N} \exp\left(  - \frac{1}{2}(h(\theta) | h(\theta)) \right) I_{0}(|(d|h(\theta))|)\,.
\end{aligned} 
$${#eq-phase-marginalized-likelihood}

The function $I_{0}$ appearing in the last expression is a modified Bessel function of the first kind, the solution to the following integral:
$$
I_{0}(\sqrt{ A^{2} + B^{2} }) = \frac{1}{2 \pi} \int_{0}^{2\pi} \exp(A \cos \phi + B\sin \phi) \text{d} \phi\,.
$$

#### Recovering phase from marginalized samples

Since the analytical likelihood is known, it is possible to sample the phase after having performed a run with a phase-marginalized likelihood [@thraneIntroductionBayesianInference2019]. 

For any given sample $\theta$ from a phase-marginalized posterior we can write the posterior as a function of $\phi_{c}$, conditioned on $\theta$: the integrand in equation @eq-phase-marginalized-likelihood. 

### Distance

