---
format:
    html:
        code-fold: true
        bibliography: ../../rehear.bib
        execute:
            debug: false
    pdf:
        execute:
            echo: false
        bibliography: ../../rehear.bib
---

```{python}
from thesis_scripts import *
```

# Parameter estimation

When performing the analysis of some data $d$ according to some model $M$ parameterized by some finite number of parameters $\theta$, we employ Bayes' theorem, which is derived by expressing the joint probability $\text{prob}(d, \theta | M)$ in two different ways: 

$$ \text{prob}(d, \theta | M) = \mathcal{L}(d | \theta, M) \pi (\theta | M) = p(\theta | d, M) \mathcal{Z}(d | M)\,.
$$

The entries in this equation are: 

- the _likelihood_ $\mathcal{L}$ of the data given the model and a specific choice of its parameters - it is a probability distribution over the data (i.e. $\int \mathcal{L}(d|\theta, M) \text{d}d = 1$), but we interpret it as a function of the parameters $\theta$ while the data are fixed;
- the _prior_ $\pi$ - a representation of our beliefs about the model's parameters before seeing the data;
- the _posterior_ $p$ for the model's parameters - a representation of our updated beliefs about them after seeing the data;
- the _evidence_ $\mathcal{Z}$ for the model - a normalization constant for the posterior, or the likelihood for the data marginalized over all the model's parameters.

The likelihood and prior are part of the problem definition, and can typically be readily computed at any given value of the parameters.
What we refer to as "computing the posterior" means obtaining a useful representation for it. 
If the parameter space is high-dimensional, evaluating the likelihood on a grid quickly becomes unpractical. A common solution to this issue is to use stochastic methods such as nested sampling [@sec-nested-sampling], which allow us to obtain a set of samples $\theta _i$ distributed according to the posterior.
This way of representing a posterior is convenient, since we can easily compute summary statistics from it, such as the expectation value of any function $f(\theta)$:

$$ \langle f \rangle \approx \frac{1}{N} \sum _{i=1}^N f(\theta _i) \,.
$$

## Fisher matrix

In the Fisher matrix approximation, we are considering the 
gravitational wave likelihood as if it was written like 

$$ \mathcal{L}(d | \theta) \approx \mathcal{N} \exp \left(- \frac{1}{2} \Delta \theta^i \mathcal{F}_{ij} \Delta \theta^j \right)
$$

for some normalization $\mathcal{N}$, where $\Delta \theta^i = \theta ^i - \langle \theta ^i \rangle$ denotes the deviation of the parameters from their mean values and where we are using the Einstein summation convention.

This is the expression of a multivariate normal distribution, with covariance matrix $\mathcal{C}_{ij} = \mathcal{F}_{ij}^{-1}$.

The Fisher matrix $\mathcal{F}_{ij}$ can be computed as the scalar product
of the derivatives of waveforms: 
$$ \mathcal{F}_{ij} = \left.\left\langle \partial_i \partial_j \mathcal{L} \right\rangle \right|_{n = 0,\ \theta = \langle \theta \rangle} =  ( \partial_i h | \partial_j h ) = \Re \int_0^{\infty} \frac{1}{S_n(f)}  \frac{\partial h}{\partial \theta _i} \frac{\partial h^*}{\partial \theta _j}\text{d}f\,.
$$

These derivatives may be computed numerically or analytically.

### Derivation

For a more in-depth derivation refer to @finnDetectionMeasurementGravitational1992; here we just give a simple argument.
We can rewrite the derivatives of the log-likelihood as follows:

$$ \begin{aligned}
\partial_i \partial_j \log \mathcal{L} &= \frac{1}{2} \partial_i \partial_j (d-h|d-h) \\
&= \frac{1}{2} \partial_i \partial_j \left((d|d) - 2 (d|h) + (h|h)\right) \\
&=  \partial_i \left(-  (d|\partial_j h) + (\partial_j h|h)\right) \\
&=  \left(-  (d|\partial_i \partial_j h) + (\partial_i \partial_j h|h) + (\partial_i h | \partial_j h)\right) \\
&=  -(n|\partial_i \partial_j h)  + (\partial_i h | \partial_j h) 
\end{aligned}
$$

and then, since we are evaluating this quantity at the maximum-likelihood realization of the noise $n = 0$, the term $(n|\partial_i \partial_j h)$ is equal to zero.

### Conditioning versus marginalizing

It is important to include all parameters when performing a Fisher matrix analysis.
This is because not including a parameter which correlates to the one we care about in 
the Fisher analysis is equivalent to __conditioning__ upon it having that specific value, 
while the correct operation to be performed is __marginalizing__ over all possible values.

Here is a graphical way to see the difference between conditioning and marginalizing 
for correlated variables.

```{python}
from thesis_scripts.multivariate_normal import MultivariateNormal
n = MultivariateNormal([0, 0], [[1, 0.8], [0.8, 1]])
n.plot_2d_analytical(0, 0, .9)
```

When dealing with the _correlation matrix_ marginalizing 
simply amounts to ignoring some parameters, but crucially
in the _Fisher matrix_ this is not the case, since the 
inversion introduces mixing between the parameters.

## Nested sampling {#sec-nested-sampling}

Nested sampling, introduced by Skilling in 2006 [@skillingNestedSamplingGeneral2006], is an algorithm designed to compute the _evidence_ $\mathcal{Z}$ as well as the posterior distribution on the parameters. 

The evidence is computed through the integral

$$ \mathcal{Z}(d|M) = \int \mathcal{L}(d | \theta, M) \pi (\theta | M) \text{d}^n\theta \,.
$$

This integral is in $n$ dimensions (where $n$ is the dimensionality of the parameter space) and therefore difficult to work with. The idea in nested sampling is to rewrite it in terms of the auxiliary variable $\xi$ (employing the notation of @siviaDataAnalysisBayesian2006), defined as the prior volume contained within a likelihood constraint $\mathcal{L} \geq L$:

$$ \xi (L) = \int_{\mathcal{L}(d | \theta, M) \geq L} \pi (\theta | M) \text{d}^n\theta\,.
$$

Since the prior is a normalized probability distribution and the likelihood ranges from 0 to $L _{\text{max}}$, this variable will range from $\xi(0) = 1$ to $\xi(L _{\text{max}}) = 0$, and it will always be decreasing.[^1]
We can define its inverse, $L(\xi)$, 
and rewrite the likelihood integral through integration by parts: the evidence is the expectation value of the likelihood, therefore 
$$
\mathcal{Z}(d|M) = \int_{0}^{L_\text{max}} \xi(L) \text{d}L 
= \xi L |_{L=0}^{L=L_\text{max}} - \int_{\xi(L=0)}^{\xi(L=L_\text{max})} L(\xi)\text{d}\xi = \int_{0}^{1}L(\xi)\text{d}\xi\,.
$$ {#eq-evidence-integral}

For a detailed discussion of the mathematical details, also see [@ashtonNestedSamplingPhysical2022].

### Prior compression {#sec-prior-compression}

Note that, by definition, $\xi$ is directly related to probability mass: the prior probability of an interval $[\xi_{0}, \xi_{1}]$, i.e. the prior mass which has likelihood values $L(\xi_{0}) < \mathcal{L} < L(\xi_{1})$, is 

$$
p([\xi_{0}, \xi_{1}]) = \int _{L(\xi_{0}) < \mathcal{L}(d|\theta, M) < L(\xi_{1})} \pi (\theta | M) \text{d}^{n} \theta = \xi_{1} - \xi_{0}\,,
$$

where we computed the integral on a likelihood "ring" by subtracting the inside volume from the outside one.
This is useful to us, since it means that if we distribute points uniformly according to the prior their $\xi$ values will also be uniformly distributed in $[0, 1]$.

If $k$ points are uniformly distributed in an interval $[0, \xi^*]$, then the largest of them will have a $\xi$ coordinate distributed as $\xi _\text{max} / \xi^* \equiv t \sim \text{beta}(k, 1) = k t^{k-1}$,[^2] where we defined the _compression ratio_ $t$: when we discard the lowest-likelihood point with $\xi _\text{max}$, we will have contracted the prior volume by a factor $t$.
In terms of $\log t$, the distribution reads 
$$
\frac{\text{d}p}{\text{d}\log t} = t\frac{\text{d}p}{\text{d}t} = k t^{k} = k e^{k \log t}
$$

This distribution is shown in @fig-nested-sampling-volume-compression-distribution.

```{python}
#| label: fig-nested-sampling-volume-compression-distribution
#| fig-cap: "Volume compression"

from matplotlib.ticker import FixedLocator, FixedFormatter
import numpy as np
import matplotlib.pyplot as plt

n = 1
log_t = np.linspace(-3/n, 0)
p_of_log_t = n * np.exp( n * log_t)

plt.plot(log_t, p_of_log_t / n)
_ = plt.xlabel('$\log t$')
_ = plt.ylabel(r'$\mathrm{d}p / \mathrm{d} \log t$')

plt.xlim(-3/n, 0)
plt.ylim(0, n)

plt.gca().xaxis.set_major_locator(FixedLocator([-3/n, -2/n, -1/n, 0]))
plt.gca().xaxis.set_major_formatter(FixedFormatter([
	'$-3/n$', 
	'$-2/n$', 
	'$-1/n$', 
	'$0$'
]))

plt.gca().yaxis.set_major_locator(FixedLocator([0, n/4, n/2, 3*n/4, n]))
plt.gca().yaxis.set_major_formatter(FixedFormatter([
	'$0$', 
	'$n/4$', 
	'$n/2$', 
	'$3n/4$', 
	'$n$'
]))
```

Its mean and standard deviation are: 
$$
\begin{aligned}
\langle \log t \rangle &= \int_{-\infty}^{0} \log t \frac{\text{d}p}{\text{d}\log t} \text{d}\log t  \\
&= \int_{-\infty}^{0} \frac{x}{k} k e^{x} \frac{ \text{d}x}{k}  \\ 
&= \frac{1}{k} \int_{-\infty}^{0} x e^{x} \text{d}x \\
&= - \frac{1}{k}
\end{aligned}
$$

where $x = k \log t$, and
$$
\begin{aligned}
\left\langle  (\log t)^{2}  \right\rangle - \frac{1}{k^{2}}
&= \int_{-\infty}^{0} (\log t)^{2} \frac{\text{d}p}{\text{d}\log t} \text{d} \log t - \frac{1}{k^{2}} \\
&= \int_{-\infty}^{0} \frac{x^{2}}{k^{2}} k e^{x} \frac{\text{d}x}{k} - \frac{1}{k^{2}}  \\
&= \frac{1}{k^{2}} \int_{-\infty}^{0} x^{2} e^{x} \text{d}x - \frac{1}{k^{2}}  \\
&= \frac{2-1}{k^{2}} = \frac{1}{k^{2}}\,.
\end{aligned}
$$

Compactly, we can then write $\log t = (-1 \pm 1) / k$. 

### Computing evidence and posterior

If we sample $k$ points from the prior (with total volume $X_{0}$) and remove the one with the worst likelihood, the remaining prior volume will be $X_{1} = t_{1}X_{0}$, where $\log t_{1}$ has an expectation value of $-1 /k$. This will be true at every iteration, so [@skillingNestedSamplingGeneral2006, section 5]
$$
\log X_{i} = \sum_{j\leq i} \log t_{j} \approx -\frac{i}{k} \pm \frac{\sqrt{ i }}{k}
$$

The prior is compressed exponentially, which is desirable since the typical set for the posterior is often several orders of magnitude smaller than the prior.

```{python}
#| label: fig-nested-sampling-volume-compression-iteration
#| fig-cap: "Volume compression by iteration. The number of live points is denoted here as $n_{\\mathrm{live}} = k$. Note how the horizontal slices are thinner when we have more live points: increasing them will decrease the uncertainty on the prior compression obtained at a fixed iteration number. After reaching a logarithmic volume compression of $- \\log \\xi = 4$ the runs are truncated, and the remaining points are shown: these are distributed uniformly and not geometrically in $\\xi$, therefore they taper off in this logarithmic plot."

import numpy as np
import matplotlib.pyplot as plt

rng = np.random.default_rng(seed=1)

n_iterations = 80
logX_min = -4

n_live_numbers = [100, 50]
colors = ['grey', 'black']

for n_live, color in zip(n_live_numbers, colors):

	results = [[] for _ in range(n_iterations)]

	for i in range(n_iterations):
		points = rng.uniform(size=n_live)
		points = np.sort(points)
		logX = 0
		while logX > logX_min:
			results[i].append(logX)
			logX = np.log(points[-1])
			points[-1] = rng.uniform(0, np.exp(logX))
			points = np.sort(points)
		results[i].extend(np.log(points[::-1]))

	min_i = min(len(arr) for arr in results)

	for i in range(n_iterations):
		if i == 0:
			label = '$n_{\mathrm{live}} =$' + f' {n_live}'
		else:
			label = None
		plt.plot(
			results[i], 
			np.arange(len(results[i])), 
			c=color, 
			alpha=.2, 
			label=label)

plt.legend()
plt.axvline(logX_min, ls='--', c='black', lw=1)
plt.xlim(0, logX_min-6)
plt.xlabel(r'$\log \xi$: prior compression')
plt.ylabel('Iteration number')
plt.show()
```

This allows us to construct a procedure to evaluate the integral in @eq-evidence-integral, as long as we are able to do the following:

1. sample uniformly $k$ points from the prior
2. find the lowest-likelihood point $\theta_{1}$ and discard it: now the prior volume is approximately $\xi_{1} = e^{-1/k}$; let us denote its likelihood as $L_{1}$
3. sample a new point $\theta_{2}$ uniformly from the prior, constrained to $L_{2} = L(\theta_{2}) > L_{1}$
4. repeat from point 2.

We are constructing a sequence of points $\theta_{i}$ with corresponding likelihoods $L_{i}$ and approximate associated interior prior volumes $\xi_{i} \approx e^{-i/k}$. 
At this stage, we still need to discuss how step 3 is performed, as well as when the iteration should stop - for now, suppose that happens at some stage $n_\text{iter}$.

For the evidence, we can simply use a trapezoidal integration rule: 
$$
\mathcal{Z}(d|M) \approx  \sum_{i=1}^{n_\text{iter}} w_{i} L_{i} = \sum_{i=1}^{n_\text{iter}} \frac{\xi_{i+1} - \xi_{i-1}}{2} L_{i} 
$$

It can be shown that this sum converges to the correct value in the $n_\text{iter} \to \infty$ and $n _\text{live} \to \infty$ limit.

These weights can also be used to estimate the posterior as follows: take the points $\theta_{i}$ and assign to each of them a weight 
$$
p_{i} = \frac{w_{i} L_{i}}{Z}\,.
$$
It is readily seen that these weights add to 1, and heuristically they are computed as one might expect, by multiplying the prior mass and likelihood value for each of the regions we have subdivided the prior volume into.

Often one is be interested in a set of equally-weighted samples: these can be obtained, for example, through density estimation methods.

### Commonly used plots

These quantities can be tracked through a Nested Sampling run as a useful diagnostic. 
Here we show some commonly used plots, based on a two-dimensional example run with a Gaussian covariance.

```{python}
import numpy as np
from dynesty import NestedSampler

# from the Dynesty quickstart: 
# https://dynesty.readthedocs.io/en/latest/quickstart.html
ndim = 2

# Define our 3-D correlated multivariate normal log-likelihood.
std = 3e-2
mu = 0.5 * np.ones(ndim)
C = np.identity(ndim) * std**2
C[C==0] = 0.95 * std**2
Cinv = np.linalg.inv(C)
lnorm = -0.5 * (np.log(2 * np.pi) * ndim +
                np.log(np.linalg.det(C)))

def loglike(x):	
    return -0.5 * np.dot(x-mu, np.dot(Cinv, x-mu)) + lnorm

def ptform(u):
    return u

fname = data_path / 'cache' / 'plotting_example_sampler.pkl'

if fname.exists():
	sampler = NestedSampler.restore(str(fname))
else:
	sampler = NestedSampler(loglike, ptform, ndim, nlive=400)
	sampler.run_nested(dlogz=0.01)
	sampler.save(str(fname))
```

The following plots are showing, all as a function of the prior compression $\log X$: 

- the number of live points, which is constant up to the point where the nested sampling run is stopped: then, the remaining points are reused;
- the likelihood $L_i$, which is strictly increasing as expected;
- the posterior mass $w_i L_i / Z$, which increases and then decreases: first, the likelihood's increase dominates, but at some point its values start tapering, and the decrease in prior volume $w_i$ dominates;
- the accumulation

```{python}
from dynesty import plotting as dyplot
lnz_truth = 0
fig, axes = dyplot.runplot(sampler.results, lnz_truth=lnz_truth)
fig.set_size_inches(8, 12)
```

The following plot is called a _trace plot_: 

```{python}
fig, axes = dyplot.traceplot(
	sampler.results, 
	truths=np.zeros(ndim),
	truth_color='black', 
	show_titles=False,
	trace_cmap='inferno', 
	connect=True,
	connect_highlight=range(2)
)
fig.set_size_inches(8, 6)

```

Finally, what we often care about: a corner plot of the results:

```{python}
_ = dyplot.cornerplot(
	sampler.results, 
	color='blue', 
	truths=np.zeros(ndim),
	truth_color='black', 
	show_titles=True,
	max_n_ticks=3, 
	quantiles=None,
)
```

### Information gain

The typical set of the posterior is often much smaller than the prior: how can this be quantified?

The KL divergence is defined as 

$$ KL(p \parallel \pi) = \int p(\theta ) \log \left( \frac{ p( \theta )}{\pi (\theta )}\right) \text{d}\theta \,.
$$

This quantity can be understood as a "volumetric compression" from the prior to the posterior.
If the distributions are flat, this intuition is exact [@petrosyanSuperNestAcceleratedNested2022]: suppose we have $\pi (\theta) \equiv [\theta \in V_{\pi}] / V_{\pi}$ and $p(\theta) \equiv [\theta \in V_{p}] / V_{p}$, where the two volumes are such that $V_{p} \subset V_{\pi}$. Then,  
$$
KL (p \parallel \pi) = \int_{V_{\pi}} \frac{[\theta \in V_{p}]}{V_{p}} \log \frac{V_{\pi}}{V_{p}} \text{d}\theta = \log \frac{V_{\pi}}{V_{p}},
$$

since the integral can be restricted to the $V_{p}$ volume directly.

For the previous example:[^3]

```{python}
print(f'H = {sampler.results.information[-1]}')
print(f'theoretical H = {-ndim/2 * (1+np.log(2 * np.pi)) - .5 * np.log(np.linalg.det(C))}')
```



[^1]: It will not necessarily be _strictly_ decreasing, but that is not a conceptual issue. One can introduce jitter in the likelihood, varying it at each point by an inconsequential amount, in order to ensure that the decreasing condition is verified precisely.
[^2]: In general, the $n$-th smallest out of $k$ uniform random variates in $[0, 1]$ is distributed according to $\text{beta}(k, n-k+1) \propto x^{n-1}(1-x)^{k-n}$; here we are looking at the $k$-th smallest (i.e. the largest).
[^3]: The derivation of the entropy of a Gaussian distribution can be found [here](https://gregorygundersen.com/blog/2020/09/01/gaussian-entropy/), it is computed integrating over all of space but this is not a bad approximation, since our distribution has small width compared to the prior.