---
format:
    html:
        code-fold: true
        bibliography: ../../rehear.bib
    pdf:
        execute:
            echo: false
        bibliography: ../../rehear.bib
---
# The Lunar Gravitational Wave Antenna {#sec-lgwa}

## Detector concept

The idea of using a planetary body as a gravitational wave detector
was proposed by Joseph Weber [@weberDetectionGenerationGravitational1960], who led the efforts to deploy a gravimeter on the Moon with the Apollo 17 mission.
The Lunar Surface Gravimeter was 

### Displacement noise

```{python}
#| label: fig-lgwa-soundcheck-displacement-noise
#| fig-cap: "Displacement noise estimates for LGWA and Soundcheck."

from thesis_scripts import *
import numpy as np
import matplotlib.pyplot as plt
import astropy.units as u
import astropy.constants as ac

# there is an extra sqrt(2) in the shot noise, which is explained by the
# fact that only one the two interferometer arms picks up the signal

def get_noise_asd(ff, n_seismometers, temperature, quality_factor, m, P, dL):
	hbar = ac.hbar.si.value
	kB = ac.k_B.si.value
	c = ac.c.si.value
	laser_wavelength = 1.064e-6
	reference_frequency = 0.1

	omega0 = 2*np.pi*c/laser_wavelength

	n_shot = laser_wavelength/(2*np.pi)*np.sqrt(2*hbar*omega0/P)*np.sqrt((reference_frequency**2-ff**2)**2+(reference_frequency**2/quality_factor)**2)/ff**2

	n_freq = dL*(4e4+5e4*(0.1/ff)**1.2)/omega0*np.sqrt((reference_frequency**2-ff**2)**2+(reference_frequency**2/quality_factor)**2)/ff**2

	n_readout = np.sqrt(n_shot**2 + n_freq**2)/np.sqrt(n_seismometers)
	
	n_therm = np.sqrt(4*kB*temperature*(2*np.pi*reference_frequency)**2/(m*quality_factor*2*np.pi*ff))/(2*np.pi*ff)**2

	return np.sqrt(n_readout**2 + n_therm**2)/np.sqrt(n_seismometers)

def get_noise_asd_squid(ff, energy_resolution, critical_frequency, coupling_efficiency, suspended_mass, quality_factor, temperature, natural_frequency):
	hbar = ac.hbar.si.value
	kB = ac.k_B.si.value
	c = ac.c.si.value

	n_therm = np.sqrt(
		4*kB*temperature*(
		2*np.pi*natural_frequency)**2
		/(suspended_mass*quality_factor*2*np.pi*ff)
	) / (2*np.pi*ff)**2

	eA = energy_resolution * hbar
	omega_0 = 2 * np.pi * natural_frequency
	omega = 2 * np.pi * ff

	n_squid = np.sqrt(
		2*eA*(1+critical_frequency/ff)
		/ (suspended_mass * omega_0 * coupling_efficiency )
		 * (
			(omega**2-omega_0**2)**2 + omega_0**2 / quality_factor
		) / omega**4
	)
	return np.sqrt(n_squid**2 + n_therm**2)

ff = np.logspace(-3,1,500)

f_stab = 100

noise_params_lgwa = {
	'n_seismometers': 1, 
	'temperature': 4, 
	'quality_factor': 1e4, 
	'm': 10, 
	'P': 5e-3, 
	'dL': 1e-3/f_stab
}

noise_params_lgwa_si = {
	'energy_resolution': 50,
	'suspended_mass': 10,
	'quality_factor': 1e6,
	'critical_frequency': 0.1,
	'natural_frequency': 0.25,
	'coupling_efficiency': 0.25,
	'temperature': 5,
}

noise_params_soundcheck = {
	'n_seismometers': 1, 
	'temperature': 40, 
	'quality_factor': 1e4, 
	'm': 3, 
	'P': 5e-9, 
	'dL': 1e-3
}

noise_lgwa = get_noise_asd(ff, **noise_params_lgwa)
noise_lgwa_si = get_noise_asd_squid(ff, **noise_params_lgwa_si)
noise_soundcheck = get_noise_asd(ff, **noise_params_soundcheck)

plt.loglog(ff, noise_lgwa, label='LGWA Nb (1 seismometer)')
plt.loglog(ff, noise_lgwa_si, label='LGWA Si (1 seismometer)')
plt.loglog(ff, noise_soundcheck, label='Soundcheck')
plt.xlabel('Frequency [Hz]')
plt.ylabel('Noise ASD $[\\mathrm{{m}} / \\sqrt{{\\mathrm{{Hz}}}}]$')
plt.legend()
plt.grid('both')
```

```{python}
from thesis_scripts import data_path

psd_path = data_path / 'LGWA_Si_psd.txt'
psd_data = np.loadtxt(psd_path)

displacement_noise = get_noise_asd_squid(psd_data[:, 0], **noise_params_lgwa_si)

R_moon = 1737.4e3
lgwa_strain_asd = np.sqrt(psd_data[:, 1])

plt.loglog(psd_data[:, 0], displacement_noise / lgwa_strain_asd)

secax = plt.gca().secondary_yaxis('right', functions=(
	lambda x : x / R_moon, 
	lambda x : x * R_moon)
)
secax.set_ylabel('Response [Moon radii]')

plt.ylabel('Response model [m]')
plt.xlabel('Frequency [Hz]')
plt.show()
```

```{python}
soundcheck_displacement_noise = get_noise_asd(psd_data[:, 0], **noise_params_soundcheck)

soundcheck_psd = np.loadtxt(data_path / 'LGWA_Soundcheck_psd.txt')

plt.loglog(psd_data[:, 0], soundcheck_displacement_noise / (displacement_noise / lgwa_strain_asd), label='Recomputed Soundcheck strain ASD')
plt.loglog(soundcheck_psd[:, 0], np.sqrt(soundcheck_psd[:, 1]), label='Stored Soundcheck ASD')

plt.ylabel('Strain ASD $[\\mathrm{{m}} / \\sqrt{{\\mathrm{{Hz}}}}]$')
plt.xlabel('Frequency [Hz]')

plt.legend()
plt.plot()
```

### Computing the lunar response to gravitational waves {#sec-lgwa-response}

The LGWA will consist of seismometers measuring displacement along the horizontal direction.

As we anticipated in @sec-lgwa-antenna-patterns, the displacement corresponding to an impacting monochromatic gravitational wave can be modeled through a detection tensor
$$
\mathcal{D}_{ij}(t; f_{0}) = n_{i}(t) b_{j}(t) L(f_{0}) = \hat{D}_{ij}(t; f_{0})L(f_{0}) \,,
$$
where $n_{i}(t)$ is the normal to the lunar surface at the detector location at time $t$, while $b_{j}(t)$ is a vector parallel to the lunar surface and aligned to the measurement channel.
We compute all vectors in a fixed frame, so that the source's position is constant.

In @sec-timing-general we outlined the effect of detector motion on the waveform in the time domain. Applying a Stationary Phase Approximation, we can combine the effect of a moving detector and a rotating antenna pattern in the frequency domain: the measured frequency-domain strain will satisfy
$$
s(f) = h_{ij}(f) \mathcal{D}_{ij}(t(f); f) \exp\left( 2 \pi i f \left( t_{0} + \frac{\vec{r}(t(f)) \cdot \hat{m}}{c} \right)  \right)\,,
$${#eq-lgwa-strain-projection-spa}
where: 

- $t(f)$ is the time-to-frequency map given by the Stationary Phase Approximation (@eq-spa-time-from-phase);
- $h_{ij}(f)$ is the frequency-domain gravitational wave strain tensor;
- $\hat{m}$ is the _propagation_ unit vector (which has opposite sign to the _source position_ unit vector, and points "inward");^[As a sanity check, consider the relative signs of $t_{0}$ and this phase term: increasing $t_{0}$ means the introduction of a delay, and accordingly increasing the scalar product $\vec{r} \cdot \hat{n}$ means moving the detector further from the source, which also delays the signal's arrival.]
- $\vec{r}(t)$ is the position of the detector as a function of time, measured in an ICRS-aligned coordinate frame, centered at some point in space;
- $t_{0}$ is the reference time, _i.e._ the time at which the event which occurs at $t=0$ in the time-domain waveform $h_{ij}(t)$ reaches the center of the reference frame, $\vec{r}=0$.

Let us define an orthonormal reference frame at the lunar surface: $(a, b, n)$, where $n$ is aligned to the local normal direction, while $a$ and $b$ define the horizontal measurement directions of the two LGWA channel.
In order to compute the geometric portion of the antenna pattern tensor, $\hat{D}_{ij}$, we need to know these vectors as a function of time.
Once we have them, computed these vectors, we can recover the strain through the antenna pattern functions, which are obtained as described in @sec-antenna-patterns:
$$
\begin{aligned}
F_{+} &= (n\cdot u)(b\cdot u)-(n\cdot v)(b\cdot v)) \\
F_{\times} &= (n\cdot u)(b\cdot v)+(n\cdot v)(b\cdot u)\,.
\end{aligned}
$$

```{python}
#| label: fig-response-functions-of-time
#| fig-cap: "Response functions in terms of time."

from lgwa_response.likelihood import LunarLikelihood
import matplotlib.pyplot as plt
import numpy as np

like = LunarLikelihood()
t_0 = 1577491218.
day = 3600*24
times = np.linspace(t_0, t_0+day*28, num=1000)
hp1, hp2, hc1, hc2 = like.get_antenna_response(times, ra=0, dec=np.pi/2, psi=.9)

times_days = (times - t_0)/day

plt.plot(times_days, hp1, label='$F_+$ response, $x$ channel', color='#117733')
plt.plot(times_days, hc1, label='$F_\\times$ response, $x$ channel', color='#44AA99')
plt.plot(times_days, hp2, label='$F_+$ response, $y$ channel', color='#CC6677')
plt.plot(times_days, hc2, label='$F_\\times$ response, $y$ channel', color='#882255')
plt.legend()
plt.xlabel('Days from January 1st 2030')
plt.title('Antenna patterns for a source at declination 90 degrees')
plt.show()
```

::: {#nte-scalar-products-spherical .callout-note collapse="true"}
##### Scalar products in spherical coordinates

The scalar product between two unit vectors in spherical coordinates can be computed from their colatitudes and azimuths as follows:
$$
a\cdot b = \cos \theta_{a} \cos\theta_{b} + \sin \theta_{a} \sin \theta_{b} \cos(\phi_{a} - \phi_{b})\,.
$$
:::

Computing these vectors can be somewhat expensive (on the scale of tens of milliseconds per evaluation), and their variation is relatively slow, on the scale of a month.
Therefore, it is advantageous to pre-compute them on a grid, cache the results and interpolate them as required.
We compute them in an ICRS frame with the `lunarsky` package [@lanmanAelanmanLunarsky2024].
We store them in spherical coordinates, with which we can still directly compute any scalar products (@nte-scalar-products-spherical).

::: {#nte-lgwa-location .callout-note collapse="true"}
##### The position of the LGWA

The precise location of the LGWA is a required input for the computation of these vectors as a function of time. It is defined by three angles: lunar latitude, lunar longitude and azimuth of one LGWA arm, the other being perpendicular to it. 

We choose a lunar latitude of 88.5 degrees, a longitude of 290 degrees, and an azimuth of 0.
These parameters were obtained through a preliminary site selection study [@gobeSeismicInvestigationLunar2025].

:::

In order to evaluate how dense the interpolation grid must be to satisfy a given accuracy requirement, we compute it with different grid sizes for a duration of 10 years,^[Specifcally, from 2030 to 2040.] and for each grid size we:

- uniformly sample a moment in time $t$ within the interpolation region;
- uniformly sample a unit vector $u$ on the sphere;
- compute the error in the scalar products, $|u \cdot (n^{\text{interp}}(t) - n^{\text{true}}(t)|$ and similarly for $a$ and $b$.

As figure @fig-response-interpolation-errors shows, we can achieve errors on the scale of $10^{-4}$ on the scalar products with only $10^{4}$ points, which take about a minute to compute, and adding more as required is easy.
Linear interpolation is sufficient to achieve this level of accuracy.

```{python}
#| label: fig-response-interpolation-errors
#| fig-cap: "Errors in scalar products computed with an interpolated version of the detector-centric basis vectors. The errors are computed from 400 randomly sampled points in the sky and time. Since the detector is located near the pole, the normal vector varies less across the month, and is therefore easier to interpolate."

from lgwa_response.lunar_coordinates import make_response_interpolation_plot
from thesis_scripts import data_path
cache_path = data_path / 'cache'

make_response_interpolation_plot(cache_path)
```

In order to compute the strain in @eq-lgwa-strain-projection-spa we also need the detector position. 
We apply the interpolation approach here as well, pre-computing the position on an equally spaced grid, and we can run a similar test to that in @fig-response-interpolation-errors to determine how fine the interpolation grid needs to be.
 
The results in figure @fig-position-interpolation-errors show that in order to
achieve an error of $10^{-4}$ radians we need as many as 160 thousand interpolation points for the 10-year span we are considering. 
The maximum phase error is computed by comparing the position error to the angular wavelength corresponding to the smallest angular wavelength in the LGWA band (i.e. the highest frequency): $c/(2 \pi \times 3 \mathrm{Hz}) \approx 1.6 \times 10^7 \mathrm{m}$.
This is the worst-case scenario, as to achieve it we would need a source at the upper edge of the detector's band to also be perfectly aligned with the position error vector $\vec{r} _\text{interp} - \vec{r}_\text{true}$.

```{python}
#| label: fig-position-interpolation-errors
#| fig-cap: "Interpolation errors in position, by the number of interpolation points."

from lgwa_response.lunar_coordinates import make_position_interpolation_plot
from thesis_scripts import data_path
cache_path = data_path / 'cache'

make_position_interpolation_plot(cache_path)
```

The position interpolation requires about 10 times more points to achieve a comparable level of accuracy, but each evaluation of the position of the detector is roughly 10 times faster than an evaluation of the basis vectors.

In @fig-position-function-of-time we illustrate how the position vector encodes several epicycles: motion of the Earth-Moon system around the Sun, of the Moon around the Earth, and finally of the detector location from the lunar center.

```{python}
#| label: fig-position-function-of-time
#| fig-cap: "Position of the detector as a function of time."

from lgwa_response.likelihood import LunarLikelihood
from astropy.coordinates import get_body_barycentric
from astropy.time import Time
import numpy as np
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings('ignore', module='erfa')


like = LunarLikelihood()
t_0 = 1577491218.

times = np.linspace(t_0, t_0+3600*24*29.5*4, num=1000)

earth = get_body_barycentric('earth', Time(times, format='gps'), ephemeris='jpl')
earth.representation_type = 'cartesian'

moon = get_body_barycentric('moon', Time(times, format='gps'), ephemeris='jpl')
moon.representation_type = 'cartesian'

x, y, z = like.get_detector_position(times)

fig, axs = plt.subplots(3, 1, sharex=True, gridspec_kw={'hspace': .3})

x_color = '#332288'
y_color = '#44AA99'
z_color = '#CC6677'

times_lunar_months = (times - t_0)/(29.5*3600*24)

axs[0].plot(times_lunar_months, x, color=x_color, label='$x$')
axs[0].plot(times_lunar_months, y, color=y_color, label='$y$')
axs[0].plot(times_lunar_months, z, color=z_color, label='$z$')
axs[0].legend()
axs[0].set_title('Position from SSB')

axs[1].plot(times_lunar_months, x-earth.x.si.value, color=x_color)
axs[1].plot(times_lunar_months, y-earth.y.si.value, color=y_color)
axs[1].plot(times_lunar_months, z-earth.z.si.value, color=z_color)
axs[1].set_title('Position from geocenter')
axs[1].set_ylabel('Position vector [meters]')

axs[2].plot(times_lunar_months, x-moon.x.si.value, color=x_color)
axs[2].plot(times_lunar_months, y-moon.y.si.value, color=y_color)
axs[2].plot(times_lunar_months, z-moon.z.si.value, color=z_color)
axs[2].set_title('Position from lunar center')
_ = axs[2].set_xlabel('Time from January 1 2030 (lunar months)')
```





### The importance of computing time to merger correctly

In the Stationary Phase approximation, the time left until merger for a source whose phase in the frequency domain is given by $\varphi(f)$ can be computed as (Marsat and Baker 2018, eq 20)
$$
t(f) = - \frac{1}{2 \pi} \frac{\text{d}\varphi}{\text{d}f}\,.
$$

In principle this should be computed using the same expression for $\varphi$ we have in the waveform (i.e. the most accurate one available).
One may think that, however, this time can be safely approximated by using a low-order expression for $\varphi$, which will only be inaccurate at high frequency, where the time to merger is low and relative errors are less relevant.

In the Post-Newtonian approximation, the phase is given as a series in the form
$$
\varphi(f) \propto \frac{1}{\eta v^{5}} \left(
1+ \sum_{i=2}^{\infty} c_{i} v^{i}
\right)
$$
where $v = (\pi M f)^{1/3}$ and $\eta=\mu / M = m_{1} m_{2} / (m_{1} + m_{2})^{2}$.
The lowest-order expression, therefore, is $\varphi \propto \eta^{-1}(Mf)^{-5/3} = \mathcal{M}_{c}^{-5/3} f^{-5/3}$, where we define the chirp mass $\mathcal{M}_{c} = (m_{1}m_{2})^{3/5} (m_{1}+m_{2})^{1/5}$.
Reintroducing the relevant constants, this leads to the following expression for the time to merger:
$$
t_\text{lowest order}(f) = - \frac{5}{256 \pi^{8/3}} \frac{1}{\mathcal{M}_{c}^{5/3}} \frac{1}{f^{8/3}}\,.
$$

The next-order correction to this expression for the phase comes with a factor of $v^{2}\propto f^{2/3}$, which carries over during the differentiation, leading to the error scaling with $f^{-2}$.
We show this in figure @fig-time-to-merger-error: it leads to errors of several hours to days in the deci-Hertz band for a light source.

```{python}
#| label: fig-time-to-merger-error
#| fig-cap: "Error in the time to merger estimation by using the lowest-order Post-Newtonian term only. The source considered here is a neutron star binary with equal components, of 1.4 solar masses each."

import matplotlib.pyplot as plt
from lgwa_response.simple_waveforms import time_to_merger, time_to_merger_simple, Phif3hPN, SUN_MASS_SECONDS
import numpy as np

q = 1
eta = q / (1+q)**2
M = 2.8


f = np.geomspace(1e-1, 3, num=10_000)

phase = Phif3hPN(
	f, 
	M, 
	eta, 
	0., 
	0, 
	0., 
	0.
)

mchirp = M * eta**(3/5) * SUN_MASS_SECONDS

dt = (
	+time_to_merger_simple(f, mchirp)
	-time_to_merger(f, phase)
)
t = -time_to_merger(f, phase)

plt.loglog(f, t, label='Time to merger', color='#88CCEE')
plt.loglog(f, dt, label='Error by using the lowest order phase', color='#CC6677')

plt.text(f[7000], t[7000]*2, s='$\propto f^{-8/3}$')
plt.text(f[5000], dt[5000]*2, s='$\propto f^{-2}$')

plt.xlabel('Frequency [Hz]')
plt.ylabel('Time [s]')
plt.legend()

plt.show()
```

### Projected waveforms

```{python}
#| label: fig-projected-lgwa-waveforms-ratio
#| fig-cap: "Ratio of projected waveforms with slightly different declination (difference of 10 arcminutes)."

from lgwa_response.likelihood import LunarLikelihood
import numpy as np
import matplotlib.pyplot as plt

like = LunarLikelihood(gps_time_range=(1500000000., 2000000000.))
t0 = 1893024018.

f = np.geomspace(1e-1, 3, num=100000)
parameters = {
	'chirp_mass': 1.2,
	'mass_ratio': 1.,
	'time_at_center': t0,
	'inclination': 0.5,
	'phase': 0.,
	'right_ascension': 0.,
	'declination': 0.,
	'polarization': 0.,
	'luminosity_distance': 1.,
	'spin_1z': 0.,
	'spin_2z': 0.,
	'lambda_eff': 0.,
	'd_lambda': 0.,
}

hx, hy = like.projected_waveform(f, parameters)
hx2, hy2 = like.projected_waveform(f, parameters | {'declination': np.deg2rad(10/60)})

fig, axs = plt.subplots(2, 1, sharex=True)

axs[0].semilogx(f, abs(hx/hx2))
# axs[0].semilogx(f, abs(hy/hy2))

axs[1].semilogx(f, np.unwrap(np.angle(hx/hx2)), label='Center at SSB')
# axs[1].semilogx(f, np.unwrap(np.angle(hy/hy2)))

like.compute_center(t0)

hx, hy = like.projected_waveform(f, parameters)
hx2, hy2 = like.projected_waveform(f, parameters | {'declination': np.deg2rad(10/60)})


axs[1].semilogx(f, np.unwrap(np.angle(hx/hx2)), label='Center at merger-time detector location')
# axs[1].semilogx(f, np.unwrap(np.angle(hy/hy2)))
axs[1].legend()
plt.show()
```

## Scientific prospects

### Sky localization

## Reference frames for long observations

