
on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          lfs: true
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: Add venv to PATH
        run: echo "$(pwd)/.venv/bin" >> $GITHUB_PATH
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Install tinytex
        run: |
          quarto install tinytex
          TINYTEX_BIN=$(dirname "$(find "$HOME/.TinyTeX/bin" -name pdflatex | head -n 1)")
          echo "Adding $TINYTEX_BIN to PATH"
          echo "$TINYTEX_BIN" >> $GITHUB_PATH
      - name: Install extra tex packages
        run: |
          tlmgr update --self
          tlmgr install type1cm cm-super underscore dvipng
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          QUARTO_PROFILE: thesis
